'use client';
import {appPath} from '@/lib/app-path';
import {useEffect,useRef,useState} from 'react';
import {DoorOpen,LogOut,Play,RefreshCw,Trophy} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {callSchool,observeRoom,schoolLogout} from '@/lib/school/client';
import {StudentCache} from '@/lib/school/offline';
import {localId} from '@/lib/game/storage';
import type {Identity,Room,Submission,ServerResult} from '@/lib/school/contracts';
import CodeQuest from '../game/CodeQuest';
export type SchoolGame={identity:Identity;room:Room;draft:any;saveStatus:string;onSave:(draft:any)=>Promise<void>;onStart:()=>Promise<{id:string;number:number}>;onSubmit:(submission:Submission)=>Promise<ServerResult>;onExit:()=>void};
export function StudentRoom({me,roomId,onExit}:{me:any;roomId:string;onExit:()=>void}){
 const [room,setRoom]=useState<Room|null>(null),[playing,setPlaying]=useState(false),[ready,setReady]=useState(false),[error,setError]=useState(''),[saveStatus,setSaveStatus]=useState('กำลังตรวจงานที่บันทึก'),[rankings,setRankings]=useState<ServerResult[]>([]),[exitDialog,setExitDialog]=useState(false),[seconds,setSeconds]=useState(0),[draft,setDraft]=useState<any>(null),[sending,setSending]=useState(false);
 const owner=me.identity as Identity,cache=useRef<StudentCache|null>(null),pending=useRef<any>(null),attempt=useRef<any>(null),currentRoom=useRef<Room|null>(null),localWrite=useRef<Promise<void>>(Promise.resolve()),cloudBusy=useRef(false),generation=useRef(0),loadedRound=useRef('');currentRoom.current=room;
 const queuedScore=useRef<{attemptId:string;submission:Submission}|null>(null),scoreBusy=useRef(false),latestDraft=useRef<any>(null),saveSequence=useRef(0);
 const writeLocal=async(value=latestDraft.current)=>{if(!cache.current||!currentRoom.current)throw Error('ยังเก็บงานออฟไลน์ไม่ได้');const sequence=++saveSequence.current,payload={draft:value,attempt:attempt.current,pendingSubmission:queuedScore.current,savedAt:Date.now()};localWrite.current=cache.current.save(currentRoom.current.roundId,payload);try{await localWrite.current}catch(e){setSaveStatus('เก็บงานบนเครื่องไม่สำเร็จ กรุณาเก็บโปรแกรมเป็นไฟล์');throw e}if(sequence===saveSequence.current)setDraft(value);};
 const persist=async(value:any)=>{latestDraft.current=value;pending.current=value;await writeLocal(value);setSaveStatus(navigator.onLine?'เก็บงานเข้ารหัสแล้ว · รอส่งโรงเรียน':'ออฟไลน์ · เก็บงานเข้ารหัสแล้ว')};
 const sendQueuedScore=async()=>{const item=queuedScore.current;if(!item||scoreBusy.current||!navigator.onLine)return;scoreBusy.current=true;setSending(true);try{const result=await callSchool<ServerResult>('submit',item);if(queuedScore.current===item){queuedScore.current=null;await writeLocal();setSaveStatus(`บันทึกคะแนน ${result.score}/100 แล้ว`)}return result}finally{scoreBusy.current=false;setSending(false)}};
 const flush=async()=>{if(!currentRoom.current||!navigator.onLine)return;if(queuedScore.current)await sendQueuedScore();if(!pending.current||cloudBusy.current)return;cloudBusy.current=true;const value=pending.current,r=currentRoom.current;try{await callSchool('saveWorkspace',{roomId:r.id,roundId:r.roundId,draft:{...value,attempt:attempt.current,pendingSubmission:queuedScore.current,savedAt:Date.now()}});if(pending.current===value)pending.current=null;setSaveStatus('โรงเรียนยืนยันการบันทึกแล้ว')}catch(e){setSaveStatus('เก็บงานบนเครื่องแล้ว · ยังส่งโรงเรียนไม่สำเร็จ');throw e}finally{cloudBusy.current=false}};
 useEffect(()=>{let stop:(()=>void)|undefined,alive=true;const gen=++generation.current;try{if(!me.cacheKey)throw Error('ยังไม่ได้รับสิทธิ์เก็บงาน กรุณาเข้าระบบใหม่');cache.current=new StudentCache(owner,me.cacheKey)}catch(e){setError((e as Error).message);return}const load=async(r:Room)=>{currentRoom.current=r;setRoom(r);if(loadedRound.current!==r.roundId){loadedRound.current=r.roundId;setPlaying(false);setReady(false);await localWrite.current.catch(()=>{});pending.current=null;attempt.current=null;queuedScore.current=null;let local:any=null;try{local=await cache.current!.load(r.roundId)}catch(e){setError((e as Error).message)}let remote:any=null;try{remote=await callSchool('loadWorkspace',{roomId})}catch(e){setError((e as Error).message)}if(!alive||generation.current!==gen||loadedRound.current!==r.roundId)return;const useLocal=local&&(!remote?.draft||Number(local.savedAt||0)>=Number(remote.draft.savedAt||0));const value=useLocal?local.draft:remote?.draft||null;attempt.current=useLocal?local.attempt:remote?.draft?.attempt||null;queuedScore.current=useLocal?local.pendingSubmission:remote?.draft?.pendingSubmission||null;latestDraft.current=value;pending.current=useLocal?value:null;setDraft(value);setReady(true);setSaveStatus(value?'กู้โปรแกรมของนักเรียนคนนี้แล้ว':'พร้อมเริ่มด่านใหม่');flush().catch(e=>alive&&setError(e.message))}if(r.leaderboard)callSchool<ServerResult[]>('rankings',{roomId}).then(v=>alive&&setRankings(v)).catch(e=>alive&&setError(e.message));else setRankings([])};observeRoom(owner.schoolId,roomId,load,e=>setError(e.message)).then(fn=>alive?stop=fn:fn());const heartbeat=setInterval(()=>{callSchool('heartbeat',{roomId}).catch(e=>setError(e.message));flush().catch(e=>setError(e.message))},20000),clock=setInterval(()=>setSeconds(Math.floor(Date.now()/1000)),1000);const online=()=>{setSaveStatus('เชื่อมต่อกลับสำเร็จ · กำลังส่งงานที่ค้าง');flush().catch(e=>setError(e.message))},offline=()=>setSaveStatus('การเชื่อมต่อขาดหาย · เล่นต่อและเก็บงานเข้ารหัสบนเครื่อง');window.addEventListener('online',online);window.addEventListener('offline',offline);return()=>{alive=false;generation.current++;stop?.();clearInterval(heartbeat);clearInterval(clock);window.removeEventListener('online',online);window.removeEventListener('offline',offline);cache.current?.cancel()}},[roomId,owner.uid]);
 async function start(){if(!room||room.status!=='ACTIVE'||Date.now()<room.startsAt)throw Error('รอครูเริ่มหรือเล่นต่อ');if(queuedScore.current){await sendQueuedScore();if(queuedScore.current)throw Error('ส่งคะแนนที่ค้างก่อนเริ่มครั้งใหม่')}setSending(true);try{const a=await callSchool('startAttempt',{roomId,requestId:localId()});attempt.current=a;await writeLocal();return a}finally{setSending(false)}}
 async function submit(submission:Submission){if(!attempt.current)throw Error('ไม่พบการเริ่มเล่นจากโรงเรียน');queuedScore.current={attemptId:attempt.current.id,submission};await writeLocal();try{const result=await sendQueuedScore();if(!result)throw Error('ออฟไลน์ · คะแนนรอส่งเมื่อเชื่อมต่อกลับ');return result}catch(e){setSaveStatus('เก็บคะแนนเข้ารหัสแล้ว · รอส่งซ้ำอัตโนมัติ');throw e}}
 async function retrySubmission(){try{await flush();setError('')}catch(e){setError((e as Error).message)}}
 const canPlay=room?.status==='ACTIVE'&&Date.now()>=room.startsAt,waiting=Math.max(0,Math.ceil(((room?.startsAt||0)-Date.now())/1000));
 if(playing&&room)return <><div className="school-game-bar"><span>{room.name} · รอบ {room.round} · {room.status==='PAUSED'?'ครูพักเกม':room.status==='FINISHED'?'จบรอบ':owner.name}</span><span>{sending?'กำลังติดต่อโรงเรียน':saveStatus}</span><button onClick={()=>setExitDialog(true)}>กลับห้องเรียน / เปลี่ยนคน</button></div><CodeQuest key={room.roundId} school={{identity:owner,room,draft,saveStatus,onSave:persist,onStart:start,onSubmit:submit,onExit:()=>setExitDialog(true)}}/>{renderExit()}</>;
 function renderExit(){return <Dialog open={exitDialog} onOpenChange={setExitDialog}><DialogContent className="game-dialog"><DialogHeader><DialogTitle>กลับห้องเรียน / เปลี่ยนนักเรียน</DialogTitle><DialogDescription>{saveStatus}</DialogDescription></DialogHeader><p>งานออฟไลน์เก็บแบบเข้ารหัส เปิดกลับได้เฉพาะเมื่อยืนยันตัวตนนักเรียนคนเดิม</p><button className="primary-btn" disabled={sending} onClick={async()=>{try{await localWrite.current;await flush();setPlaying(false);setExitDialog(false)}catch(e){setError((e as Error).message);setExitDialog(false)}}}>บันทึกและกลับห้องเรียน</button><button className="outline-btn" disabled={sending} onClick={async()=>{try{await localWrite.current;cache.current?.cancel();await schoolLogout();location.assign(appPath('school/'))}catch(e){setError((e as Error).message)}}}><LogOut size={16}/>ออกจากระบบ งานที่ยังไม่ส่งเก็บแยกไว้</button></DialogContent></Dialog>}
 return <main className="school-app"><div className="student-lobby"><DoorOpen size={44}/><h1>{room?.name||'กำลังเปิดห้องเรียน'}</h1><p>{owner.name} · {me.student.className}</p>{error&&<p className="school-error" role="alert">{error}</p>}{room&&<><strong className="room-code">{waiting>0?waiting:room.status==='WAITING'?'รอครูเริ่ม':room.status==='PAUSED'?'พักสักครู่':room.status==='FINISHED'?'จบรอบแล้ว':room.status==='CLOSED'?'ห้องปิดแล้ว':'พร้อมลุย!'}</strong><p>ด่าน {room.levelId} · {room.mission.level.title} · รอบ {room.round}</p><p>{room.memberCount}/40 คน · {room.mode==='challenge'?'คะแนนแข่งขันตรวจตามกติกาเกม':'กิจกรรมการเรียน'}</p><button className="primary-btn" disabled={!canPlay||!ready||sending} onClick={()=>setPlaying(true)}><Play size={18}/>เริ่ม / เล่นต่อ</button><p role="status">{saveStatus}</p>{queuedScore.current&&<button className="outline-btn" disabled={sending} onClick={retrySubmission}>ส่งคะแนนที่ค้างอีกครั้ง</button>}{room.leaderboard&&<section className="lobby-ranking"><h2><Trophy/>อันดับที่บันทึกแล้ว</h2>{rankings.length?rankings.map((r,i)=><div className="ranking-row" key={r.id}><b>{i+1}</b><span>{r.displayName}</span><strong>{r.score}</strong></div>):<p>ยังไม่มีผลคะแนน</p>}</section>}</>}<button className="outline-btn" onClick={()=>setExitDialog(true)}>กลับ / เปลี่ยนนักเรียน</button><button className="outline-btn" onClick={async()=>{try{await localWrite.current;await flush();onExit()}catch(e){setError((e as Error).message)}}}>หน้าข้อมูลนักเรียน</button></div>{renderExit()}</main>
}
