import { assetOperation } from './assets';
import { getApps,initializeApp } from 'firebase-admin/app';
import { getAuth } from 'firebase-admin/auth';
import { getFirestore,FieldValue,Transaction,DocumentReference } from 'firebase-admin/firestore';
import { createHash,randomBytes,randomInt,randomUUID,scryptSync,timingSafeEqual } from 'node:crypto';
import { z } from 'zod';
import { LEVELS,getLevel,WORLDS } from '../../../lib/game/curriculum';
import { generateMap } from '../../../lib/game/engine';
import { validateMission } from '../../../lib/school/mission-config';
import { DEFAULT_WEIGHTS,Identity,MissionSettings,Room,Submission } from '../../../lib/school/contracts';
import { compareResults,replaySubmission } from '../../../lib/school/replay';
if(!getApps().length)initializeApp();
export const db=getFirestore();
const stamp=()=>FieldValue.serverTimestamp(),hash=(v:string)=>createHash('sha256').update(v).digest('hex'),id=z.string().regex(/^[A-Za-z0-9_-]{1,128}$/),text=z.string().trim().min(1).max(120),opt=z.string().trim().max(120).default('');
type Data=Record<string,any>;
export class DomainError extends Error{constructor(public code:string,message:string){super(message)}}
const fail=(message:string,code='failed-precondition'):never=>{throw new DomainError(code,message)};
const school=(sid:string)=>db.collection('schools').doc(sid),ref=(sid:string,col:string,key:string)=>school(sid).collection(col).doc(key);
const data=(doc:any)=>doc.exists?{...doc.data(),id:doc.id}:null;
const clean=(v:any):any=>v?.toMillis?v.toMillis():Array.isArray(v)?v.map(clean):v&&typeof v==='object'?Object.fromEntries(Object.entries(v).map(([k,x])=>[k,clean(x)])):v;
const audit=(tx:Transaction,u:Identity,action:string,target:string,detail:Data={})=>tx.set(ref(u.schoolId,'system_logs',randomUUID()),{action,target,actor:u.uid,role:u.role,schoolId:u.schoolId,detail,createdAt:stamp()});
const defaults=(levelId:number):MissionSettings=>({level:structuredClone(getLevel(levelId)),active:true,energy:false,startEnergy:40,costs:{move:1,turn:1,pick:2,drop:2},weights:{...DEFAULT_WEIGHTS}});
async function identity(uid:string):Promise<Identity>{const u=data(await db.doc(`users/${uid}`).get());if(!u||!u.active)fail('บัญชีนี้ยังไม่ได้รับสิทธิ์ หรือถูกปิดใช้งาน','permission-denied');if(u.role==='student'){const s=data(await ref(u.schoolId,'students',u.studentId).get());if(!s||s.status!=='active'||s.credentialVersion!==u.credentialVersion)fail('สิทธิ์นักเรียนหมดอายุ กรุณาเข้าสู่ระบบใหม่','permission-denied')}return {...u,uid}as Identity;}
function staff(u:Identity,admin=false){if(!['admin','teacher'].includes(u.role)||(admin&&u.role!=='admin'))fail('ไม่มีสิทธิ์ทำรายการนี้','permission-denied')}
async function classAccess(u:Identity,classId:string,tx?:Transaction){const r=ref(u.schoolId,'classes',id.parse(classId)),d=data(await(tx?tx.get(r):r.get()));if(!d||d.status!=='active'||(u.role!=='admin'&&!d.teacherIds.includes(u.uid)))fail('ไม่มีสิทธิ์จัดการห้องเรียนนี้','permission-denied');return d;}
async function studentAccess(u:Identity,studentId:string,tx?:Transaction){const r=ref(u.schoolId,'students',id.parse(studentId)),s=data(await(tx?tx.get(r):r.get()));if(!s)fail('ไม่พบนักเรียน');if(u.role==='student'){if(u.studentId!==studentId)fail('ไม่มีสิทธิ์อ่านนักเรียนคนอื่น','permission-denied')}else if(u.role!=='admin'){if(!s.classId)fail('นักเรียนยังไม่มีห้องที่คุณรับผิดชอบ','permission-denied');await classAccess(u,s.classId,tx)}return s;}
async function classes(u:Identity){staff(u);let q:any=school(u.schoolId).collection('classes');if(u.role==='teacher')q=q.where('teacherIds','array-contains',u.uid);return(await q.limit(500).get()).docs.map(data);}
async function listStudents(u:Identity,p:Data){staff(u);const cs=await classes(u),allowed=cs.map((c:any)=>c.id);if(p.classId&&!allowed.includes(p.classId))fail('ไม่มีสิทธิ์อ่านห้องนี้','permission-denied');const q=await school(u.schoolId).collection('students').limit(2000).get();let rows=q.docs.map(data).filter((s:any)=>u.role==='admin'||allowed.includes(s.classId));if(p.classId)rows=rows.filter(s=>s.classId===p.classId);if(p.status)rows=rows.filter(s=>s.status===p.status);if(p.academicYear)rows=rows.filter(s=>s.academicYear===Number(p.academicYear));if(p.semester)rows=rows.filter(s=>s.semester===Number(p.semester));if(p.grade)rows=rows.filter(s=>cs.find((c:any)=>c.id===s.classId)?.grade===p.grade);if(p.search){const k=String(p.search).trim().toLocaleLowerCase();rows=rows.filter(s=>[s.studentCode,s.firstName,s.lastName,s.nickname].join(' ').toLocaleLowerCase().includes(k))}rows.sort((a,b)=>p.sort==='name'?a.firstName.localeCompare(b.firstName,'th'):p.sort==='code'?a.studentCode.localeCompare(b.studentCode):a.studentNumber-b.studentNumber||a.studentCode.localeCompare(b.studentCode));const page=Math.max(1,Math.min(100,Number(p.page)||1)),size=Math.min(100,Math.max(1,Number(p.pageSize)||25));return{rows:rows.slice((page-1)*size,page*size).map(({credentialVersion,...s}:any)=>s),total:rows.length,page,pageSize:size};}
const studentSchema=z.object({studentCode:text.max(40),prefix:opt,firstName:text,lastName:text,nickname:opt,classId:id,studentNumber:z.coerce.number().int().min(1).max(9999),status:z.enum(['active','inactive','graduated','transferred']).default('active')});
async function upsertStudent(u:Identity,input:Data,options:{dry?:boolean;jobId?:string;rowId?:string;mode?:string}={}){
 staff(u);const v=studentSchema.parse(input),code=v.studentCode.toUpperCase(),codeRef=ref(u.schoolId,'student_code_keys',hash(code));const rowRef=options.jobId?ref(u.schoolId,'student_import_jobs',u.uid+'_'+id.parse(options.jobId)).collection('rows').doc(id.parse(options.rowId)):null,payloadHash=hash(JSON.stringify(v)+options.mode);
 return db.runTransaction(async tx=>{const row=rowRef?data(await tx.get(rowRef)):null;if(row){if(row.payloadHash!==payloadHash)fail('รหัสงานนำเข้าถูกใช้กับข้อมูลอื่นแล้ว');if(row.status==='done')return row.result}const c=await classAccess(u,v.classId,tx),keyDoc=data(await tx.get(codeRef));let sid=input.id?id.parse(input.id):keyDoc?.studentId;
 if(input.id&&keyDoc&&keyDoc.studentId!==input.id)fail('รหัสนักเรียนซ้ำ');const old=sid?await studentAccess(u,sid,tx):null;
 if(old&&input.revision!==undefined&&input.revision!==old.revision)fail('ข้อมูลถูกแก้ไขโดยผู้ใช้อื่น กรุณาโหลดใหม่');
 if(old&&!input.id&&!options.jobId&&!options.dry)fail('มีรหัสนักเรียนนี้แล้ว ให้เปิดแก้ไขจากรายชื่อ');sid=sid||randomUUID();
 const targetNo=ref(u.schoolId,'enrollment_number_keys',`${v.classId}_${v.studentNumber}`),slot=data(await tx.get(targetNo));if(v.status==='active'&&slot&&slot.studentId!==sid)fail('เลขที่ซ้ำในห้องเรียน');
 const changed=!old||old.classId!==v.classId||old.studentNumber!==v.studentNumber||old.status!==v.status;
 const oldEnrollment=old?.enrollmentId?ref(u.schoolId,'enrollments',old.enrollmentId):null;
 if(options.dry)return{action:old?'existing':'new',studentId:sid};
 if(old&&options.jobId&&options.mode==='skip'){const result={action:'skipped',studentId:sid};if(rowRef)tx.set(rowRef,{status:'done',payloadHash,result,updatedAt:stamp()});return result}
 const enrollmentId=changed?randomUUID():old.enrollmentId;
 const record={...v,studentCode:code,schoolId:u.schoolId,className:c.className,academicYear:c.academicYear,semester:c.semester,classIds:Array.from(new Set([...(old?.classIds||[]),v.classId])),enrollmentId,credentialVersion:old?.credentialVersion||0,revision:(old?.revision||0)+1,createdAt:old?.createdAt||stamp(),createdBy:old?.createdBy||u.uid,updatedAt:stamp(),updatedBy:u.uid};
 tx.set(ref(u.schoolId,'students',sid),record);tx.set(codeRef,{studentId:sid});if(old&&old.studentCode!==code)tx.delete(ref(u.schoolId,'student_code_keys',hash(old.studentCode)));
 if(changed){if(oldEnrollment)tx.update(oldEnrollment,{status:'ended',endedAt:stamp(),updatedBy:u.uid});if(old?.status==='active')tx.delete(ref(u.schoolId,'enrollment_number_keys',`${old.classId}_${old.studentNumber}`));tx.set(ref(u.schoolId,'enrollments',enrollmentId),{schoolId:u.schoolId,studentId:sid,classId:v.classId,className:c.className,academicYear:c.academicYear,semester:c.semester,studentNumber:v.studentNumber,status:v.status==='active'?'active':'ended',enrolledAt:stamp(),endedAt:v.status==='active'?null:stamp(),createdBy:u.uid});}
 if(v.status==='active')tx.set(targetNo,{studentId:sid,enrollmentId});else if(slot?.studentId===sid)tx.delete(targetNo);
 const result={action:old?'updated':'created',studentId:sid};if(rowRef)tx.set(rowRef,{status:'done',payloadHash,result,updatedAt:stamp()});audit(tx,u,old?(old.classId!==v.classId?'student.transferred':'student.updated'):'student.created',sid,{classId:v.classId,status:v.status,importJobId:options.jobId||null});return result;
 },{maxAttempts:20});
}
async function roomAccess(u:Identity,roomId:string,tx?:Transaction){const r=ref(u.schoolId,'rooms',id.parse(roomId)),v=data(await(tx?tx.get(r):r.get()));if(!v)fail('ไม่พบห้องเกม');if(u.role==='student'){if(!v.members[u.studentId!])fail('คุณไม่ได้เข้าห้องนี้','permission-denied');const s=await studentAccess(u,u.studentId!,tx);if(!v.classIds.includes(s.classId)||s.status!=='active')fail('สิทธิ์เข้าเรียนเปลี่ยนแปลง กรุณาติดต่อครู','permission-denied')}else{staff(u);for(const c of v.classIds)await classAccess(u,c,tx)}return v as Room;}
async function rateLimit(key:string,max:number){const r=db.doc(`entry_limits/${hash(key)}`);await db.runTransaction(async tx=>{const v=data(await tx.get(r)),now=Date.now(),fresh=!v||v.resetAt<now,count=fresh?1:v.count+1;if(count>max)fail('ลองหลายครั้งเกินไป กรุณารอ 15 นาที','resource-exhausted');tx.set(r,{count,resetAt:fresh?now+900000:v.resetAt,expiresAt:new Date(now+86400000)})})}
async function join(uid:string,p:Data,ip:string){const code=z.string().regex(/^\d{6}$/).parse(p.code),studentCode=z.string().trim().min(1).max(40).parse(p.studentCode).toUpperCase();await rateLimit(`ip:${ip}`,100);await rateLimit(`code:${code}:${studentCode}`,8);const loc=data(await db.doc(`room_codes/${code}`).get());if(!loc)fail('ข้อมูลเข้าห้องไม่ถูกต้อง');const keyDoc=data(await ref(loc.schoolId,'student_code_keys',hash(studentCode)).get());if(!keyDoc)fail('ข้อมูลเข้าห้องไม่ถูกต้อง');const sid=keyDoc.studentId,cred=data(await ref(loc.schoolId,'student_credentials',sid).get()),pin=String(p.pin||'');const salt=cred?.salt||'invalid-credential-salt';const computed=scryptSync(pin,salt,32);if(!cred||!/^\d{6}$/.test(pin)||!timingSafeEqual(computed,Buffer.from(cred.hash,'hex')))fail('ข้อมูลเข้าห้องไม่ถูกต้อง');
 return db.runTransaction(async tx=>{const roomRef=ref(loc.schoolId,'rooms',loc.roomId),room=data(await tx.get(roomRef)),s=data(await tx.get(ref(loc.schoolId,'students',sid))),current=data(await tx.get(db.doc(`users/${uid}`)));if(current&&(current.role!=='student'||current.studentId!==sid||current.schoolId!==loc.schoolId))fail('ออกจากระบบก่อนเปลี่ยนนักเรียน','permission-denied');if(!s||s.status!=='active'||s.credentialVersion!==cred.version||!room||room.status==='CLOSED'||room.expiresAt<Date.now()||!room.classIds.includes(s.classId))fail('ไม่สามารถเข้าห้องนี้ได้');const snapshot=data(await tx.get(ref(loc.schoolId,'rooms',loc.roomId).collection('eligible').doc(sid)));if(room.status!=='WAITING'&&!snapshot)fail('ไม่มีรายชื่อในรอบนี้');const existing=room.members[sid];if(!existing&&(room.locked||room.status!=='WAITING'))fail('ครูล็อกห้องแล้ว');if(!existing&&room.memberCount>=40)fail('ห้องเต็มแล้ว (40 คน)');const displayName=s.nickname||`นักสำรวจ ${s.studentNumber}`,u={uid,schoolId:loc.schoolId,studentId:sid,role:'student',name:displayName,active:true,credentialVersion:s.credentialVersion};tx.set(db.doc(`users/${uid}`),{...u,updatedAt:stamp()});tx.set(ref(loc.schoolId,'room_members',`${room.id}_${sid}`),{schoolId:loc.schoolId,roomId:room.id,studentId:sid,enrollmentId:s.enrollmentId,classId:s.classId,joinedAt:stamp()},{merge:true});tx.update(roomRef,{[`members.${sid}`]:{displayName,status:existing?.status||'waiting',lastSeen:Date.now()},memberCount:room.memberCount+(existing?0:1),updatedAt:stamp()});return{identity:u,roomId:room.id};},{maxAttempts:30});
}
export async function execute(uid:string,op:string,p:Data={},ip='unknown'):Promise<any>{
 if(!uid)fail('กรุณาเข้าสู่ระบบ','unauthenticated');if(JSON.stringify(p).length>(op==='uploadAsset'?7_001_000:300000))fail('ข้อมูลใหญ่เกินไป','invalid-argument');if(op==='join')return join(uid,p,ip);const u=await identity(uid);
 if(['assets','uploadAsset','setAssetActive','loadAsset'].includes(op)){try{return await assetOperation(u,op,p)}catch(e){fail(e instanceof Error?e.message:'โมเดลไม่พร้อม','failed-precondition')}}
 if(op==='me'){const credentials=u.role==='student'?data(await ref(u.schoolId,'student_credentials',u.studentId!).get()):null;const own=u.role==='student'?await studentAccess(u,u.studentId!):null;return clean({identity:u,student:own,cacheKey:credentials?.cacheKey||null,school:data(await school(u.schoolId).get())})}
 if(op==='classes')return clean(await classes(u));
 if(op==='students')return clean(await listStudents(u,p));
 if(op==='saveStudent')return clean(await upsertStudent(u,p));
 if(op==='studentDetail'){const s=await studentAccess(u,p.studentId),history=await school(u.schoolId).collection('scores').where('studentId','==',s.id).limit(500).get(),enrollments=await school(u.schoolId).collection('enrollments').where('studentId','==',s.id).get();return clean({student:s,scores:history.docs.map(data).sort((a,b)=>Number(b.completedAt)-Number(a.completedAt)),enrollments:enrollments.docs.map(data)})}
 if(op==='import'){staff(u);const jobId=id.parse(p.jobId),rows=z.array(z.object({rowId:id,student:z.record(z.any())})).min(1).max(25).parse(p.rows);const out=[];const seenCodes=new Set(),seenNumbers=new Set();for(const row of rows){try{const c=String(row.student.studentCode).trim().toUpperCase(),n=`${row.student.classId}:${row.student.studentNumber}`;if(seenCodes.has(c)||seenNumbers.has(n))fail('รหัสหรือเลขที่ซ้ำในชุดข้อมูล');seenCodes.add(c);seenNumbers.add(n);out.push({rowId:row.rowId,ok:true,...await upsertStudent(u,row.student,{dry:!!p.preview,jobId,rowId:row.rowId,mode:p.mode==='update'?'update':'skip'})})}catch(e){out.push({rowId:row.rowId,ok:false,error:e instanceof Error?e.message:'บันทึกไม่สำเร็จ'})}}if(!p.preview)await ref(u.schoolId,'student_import_jobs',u.uid+'_'+jobId).set({schoolId:u.schoolId,createdBy:u.uid,updatedAt:stamp(),lastBatchCount:out.length},{merge:true});return out}
 if(op==='saveClass'){staff(u,true);const v=z.object({id:id.optional(),className:text,grade:text,roomNumber:text,academicYear:z.coerce.number().int().min(2500).max(2700),semester:z.coerce.number().int().min(1).max(3),teacherIds:z.array(id).max(20),status:z.enum(['active','inactive'])}).parse(p);for(const tid of v.teacherIds){const teacher=data(await db.doc(`users/${tid}`).get());if(!teacher||teacher.schoolId!==u.schoolId||!['teacher','admin'].includes(teacher.role)||!teacher.active)fail('ครูที่เลือกไม่มีสิทธิ์ในโรงเรียนนี้')}const classId=v.id||randomUUID();await db.runTransaction(async tx=>{const old=data(await tx.get(ref(u.schoolId,'classes',classId)));if(old&&(old.academicYear!==v.academicYear||old.semester!==v.semester))fail('สร้างห้องใหม่เมื่อต้องเปลี่ยนปีหรือภาคเรียน เพื่อเก็บบริบทประวัติเดิม');tx.set(ref(u.schoolId,'classes',classId),{...v,id:classId,schoolId:u.schoolId,createdAt:old?.createdAt||stamp(),createdBy:old?.createdBy||u.uid,updatedAt:stamp(),updatedBy:u.uid});audit(tx,u,'class.saved',classId)});return{id:classId}}
 if(op==='teachers'){staff(u,true);return clean((await db.collection('users').where('schoolId','==',u.schoolId).where('role','in',['teacher','admin']).limit(200).get()).docs.map(data))}
 if(op==='saveTeacher'){staff(u,true);const v=z.object({id:id.optional(),name:text,email:z.string().email().max(200),password:z.string().min(12).max(128).optional(),active:z.boolean()}).parse(p);let target=v.id;if(!target){if(!v.password)fail('กำหนดรหัสผ่านอย่างน้อย 12 ตัว');const created=await getAuth().createUser({email:v.email,password:v.password,displayName:v.name});target=created.uid;try{await db.doc(`users/${target}`).create({schoolId:u.schoolId,role:'teacher',name:v.name,email:v.email,active:v.active,createdAt:stamp(),createdBy:u.uid})}catch(e){await getAuth().deleteUser(target);throw e}}else{const old=data(await db.doc(`users/${target}`).get());if(!old||old.schoolId!==u.schoolId||old.role!=='teacher')fail('แก้ไขบัญชีนี้ไม่ได้','permission-denied');await db.doc(`users/${target}`).update({name:v.name,active:v.active,updatedAt:stamp(),updatedBy:u.uid});await getAuth().updateUser(target,{displayName:v.name,disabled:!v.active})}await db.runTransaction(async tx=>audit(tx,u,'teacher.saved',target!));return{id:target}}
 if(op==='resetPin'){staff(u);const sid=id.parse(p.studentId),pin=String(randomInt(100000,1000000)),salt=randomBytes(24).toString('hex'),pinHash=scryptSync(pin,salt,32).toString('hex');await db.runTransaction(async tx=>{const s=await studentAccess(u,sid,tx),version=(s.credentialVersion||0)+1;tx.set(ref(u.schoolId,'student_credentials',sid),{salt,hash:pinHash,version,cacheKey:randomBytes(32).toString('base64'),updatedAt:stamp(),updatedBy:u.uid});tx.update(ref(u.schoolId,'students',sid),{credentialVersion:version,updatedAt:stamp()});audit(tx,u,'student.pin_reset',sid)});return{pin}}
 if(op==='worlds'){staff(u);const saved=(await school(u.schoolId).collection('worlds').get()).docs.map(data);return WORLDS.map(w=>({...w,...saved.find(s=>Number(s.id)===w.id),id:w.id}))}
 if(op==='saveWorld'){staff(u,true);const v=z.object({id:z.number().int().min(1).max(3),name:text,sub:text}).parse(p);await db.runTransaction(async tx=>{tx.set(ref(u.schoolId,'worlds',String(v.id)),{name:v.name,sub:v.sub,updatedAt:stamp()});audit(tx,u,'world.saved',String(v.id))});return{saved:true}}
 if(op==='saveSettings'){staff(u,true);const v=z.object({name:text}).parse(p);await db.runTransaction(async tx=>{tx.update(school(u.schoolId),v);audit(tx,u,'settings.saved',u.schoolId)});return{saved:true}}
 if(op==='missions'){staff(u);const saved=(await school(u.schoolId).collection('missions').get()).docs.map(data);return clean([...LEVELS.map(l=>saved.find(m=>m.level.id===l.id)||defaults(l.id)),...saved.filter(m=>m.level.id>20)].sort((a,b)=>a.level.id-b.level.id))}
 if(op==='saveMission'){staff(u,true);let m:MissionSettings;try{m=validateMission(p)}catch(e){fail(e instanceof Error?e.message:'บทเรียนไม่ถูกต้อง','invalid-argument')}if(m!.level.assetId){const asset=data(await ref(u.schoolId,'assets',m!.level.assetId).get());if(!asset?.active)fail('โมเดลที่เลือกถูกปิดไว้หรือไม่พบ')}const levelId=m!.level.id;await db.runTransaction(async tx=>{const r=ref(u.schoolId,'missions',String(levelId));const old=data(await tx.get(r));if(p.create&&(old||levelId<=20))fail('รหัสด่านนี้มีอยู่แล้ว');tx.set(r,{...m!,updatedAt:stamp(),updatedBy:u.uid});audit(tx,u,'mission.saved',String(levelId))});return{saved:true}}
 if(op==='rooms'){if(u.role==='student')fail('นักเรียนเข้าห้องด้วยรหัสห้องเท่านั้น','permission-denied');const allowed=(await classes(u)).map((c:any)=>c.id);const rooms=(await school(u.schoolId).collection('rooms').limit(200).get()).docs.map(data).filter(r=>r.classIds.every((c:string)=>allowed.includes(c)));return clean(rooms.sort((a,b)=>b.expiresAt-a.expiresAt))}
 if(op==='createRoom'){staff(u);const v=z.object({name:text,classIds:z.array(id).min(1).max(5),levelId:z.coerce.number().int().min(1).max(999),mode:z.enum(['practice','challenge','assignment']),difficulty:z.enum(['easy','normal','hard']),timeLimit:z.coerce.number().int().min(60).max(86400),attemptLimit:z.coerce.number().int().min(1).max(100),hint:z.boolean(),leaderboard:z.boolean(),seed:z.string().regex(/^[A-Za-z0-9-]{1,64}$/).optional()}).parse(p);const cs:Data[]=[];for(const c of v.classIds)cs.push(await classAccess(u,c));if(cs.some(c=>c.academicYear!==cs[0].academicYear||c.semester!==cs[0].semester))fail('เลือกห้องในปีและภาคเรียนเดียวกัน');const savedMission=data(await ref(u.schoolId,'missions',String(v.levelId)).get());if(!savedMission&&v.levelId>20)fail('ไม่พบด่านนี้');const mission=savedMission||defaults(v.levelId);if(!mission.active)fail('ด่านนี้ถูกปิดไว้');const roomId=randomUUID(),roundId=randomUUID(),code=String(randomInt(100000,1000000)),seed=v.seed||`P4-L${v.levelId}-${randomInt(100000,999999999)}`;generateMap(mission.level,seed,v.difficulty);const worldData=data(await ref(u.schoolId,'worlds',String(mission.level.world)).get()),world={...WORLDS[mission.level.world-1],...(worldData?{name:worldData.name,sub:worldData.sub}:{})};const room={...v,world,id:roomId,code,seed,schoolId:u.schoolId,teacherIds:Array.from(new Set(cs.flatMap(c=>c.teacherIds))),academicYear:cs[0].academicYear,semester:cs[0].semester,status:'WAITING',locked:false,roundId,round:1,mission,memberCount:0,members:{},startsAt:0,pausedAt:0,pausedMs:0,expiresAt:Date.now()+7*86400000,createdBy:u.uid,createdAt:stamp(),updatedAt:stamp()};await db.runTransaction(async tx=>{if((await tx.get(db.doc(`room_codes/${code}`))).exists)fail('รหัสห้องชนกัน กรุณาลองใหม่');tx.create(ref(u.schoolId,'rooms',roomId),room);tx.create(db.doc(`room_codes/${code}`),{schoolId:u.schoolId,roomId});audit(tx,u,'room.created',roomId)});return clean(room)}
 if(op==='room'){return clean(await roomAccess(u,p.roomId))}
 if(op==='controlRoom'){staff(u);const action=z.enum(['start','pause','resume','end','new','close','lock','unlock','hintOn','hintOff','show','hide']).parse(p.action),roomId=id.parse(p.roomId);return db.runTransaction(async tx=>{const r=await roomAccess(u,roomId,tx),now=Date.now(),patch:Data={updatedAt:stamp()};let eligible:any[]=[];if(action==='start'){if(r.status!=='WAITING'||!r.memberCount)fail('เริ่มได้เมื่อมีนักเรียนในห้องรอ');const students=await tx.get(school(u.schoolId).collection('students').where('classId','in',r.classIds).where('status','==','active'));eligible=students.docs.map(data);if(eligible.length>450)fail('รายชื่อที่อนุญาตเกิน 450 คน เลือกห้องเรียนน้อยลง');Object.assign(patch,{status:'ACTIVE',locked:true,startsAt:now+3000,pausedMs:0,pausedAt:0});}if(action==='pause'){if(r.status!=='ACTIVE')fail('พักได้เฉพาะห้องที่กำลังเล่น');Object.assign(patch,{status:'PAUSED',pausedAt:now})}if(action==='resume'){if(r.status!=='PAUSED')fail('ห้องไม่ได้พักอยู่');Object.assign(patch,{status:'ACTIVE',pausedMs:r.pausedMs+now-r.pausedAt,pausedAt:0})}if(action==='end'){if(!['ACTIVE','PAUSED'].includes(r.status))fail('รอบนี้ไม่ได้กำลังเล่น');Object.assign(patch,{status:'FINISHED',finishedAt:now})}if(action==='close')patch.status='CLOSED';if(action==='new'){if(!['FINISHED','WAITING'].includes(r.status))fail('จบรอบก่อนเริ่มรอบใหม่');Object.assign(patch,{status:'WAITING',locked:false,round:r.round+1,roundId:randomUUID(),seed:`P4-L${r.levelId}-${randomInt(100000,999999999)}`,startsAt:0,pausedAt:0,pausedMs:0,members:Object.fromEntries(Object.entries(r.members).map(([k,v])=>[k,{...v,status:'waiting'}]))})}if(action==='lock'||action==='unlock')patch.locked=action==='lock';if(action==='hintOn'||action==='hintOff')patch.hint=action==='hintOn';if(action==='show'||action==='hide')patch.leaderboard=action==='show';if(action==='start'){for(const s of eligible)tx.set(ref(u.schoolId,'rooms',roomId).collection('eligible').doc(s.id),{studentId:s.id,enrollmentId:s.enrollmentId,classId:s.classId,roundId:r.roundId,academicYear:s.academicYear,semester:s.semester,studentNumber:s.studentNumber});tx.set(ref(u.schoolId,'room_rounds',r.roundId),{...r,...patch,eligibleIds:eligible.map(s=>s.id),createdAt:stamp()})}if(action==='end'||action==='close')tx.set(ref(u.schoolId,'room_rounds',r.roundId),{status:patch.status,finishedAt:now},{merge:true});tx.update(ref(u.schoolId,'rooms',roomId),patch);audit(tx,u,`room.${action}`,roomId,{roundId:r.roundId});return{saved:true}},{maxAttempts:20})}
 if(op==='heartbeat'){if(u.role!=='student')fail('สำหรับนักเรียนเท่านั้น');const r=await roomAccess(u,p.roomId),old=r.members[u.studentId!];if(Date.now()-old.lastSeen>15000)await ref(u.schoolId,'rooms',r.id).update({[`members.${u.studentId}.lastSeen`]:Date.now()});return{online:true}}
 if(op==='startAttempt'){if(u.role!=='student')fail('สำหรับนักเรียนเท่านั้น');const requestId=id.parse(p.requestId);return db.runTransaction(async tx=>{const r=await roomAccess(u,p.roomId,tx),now=Date.now(),aRef=ref(u.schoolId,'attempts',hash(`${u.studentId}:${r.roundId}:${requestId}`)),existing=data(await tx.get(aRef));if(existing)return clean(existing);if(r.status!=='ACTIVE'||now<r.startsAt)fail('รอครูเริ่มหรือกลับมาเล่นต่อ');if(now-r.startsAt-r.pausedMs>r.timeLimit*1000)fail('หมดเวลารอบนี้แล้ว');const memberRef=ref(u.schoolId,'round_players',`${r.roundId}_${u.studentId}`),member=data(await tx.get(memberRef)),eligible=data(await tx.get(ref(u.schoolId,'rooms',r.id).collection('eligible').doc(u.studentId!)));if(!eligible||eligible.roundId!==r.roundId)fail('ไม่มีสิทธิ์ในรอบนี้');const number=(member?.attempts||0)+1;if(number>r.attemptLimit)fail('ครบจำนวนครั้งที่ครูกำหนด');const a={id:aRef.id,levelId:r.levelId,schoolId:u.schoolId,studentId:u.studentId,roomId:r.id,roundId:r.roundId,mode:r.mode,number,startedAt:now,pausedMs:r.pausedMs,status:'started',...{classId:eligible.classId,enrollmentId:eligible.enrollmentId,academicYear:eligible.academicYear,semester:eligible.semester}};tx.create(aRef,a);tx.set(memberRef,{studentId:u.studentId,roomId:r.id,roundId:r.roundId,attempts:number,activeAttempt:aRef.id},{merge:true});tx.update(ref(u.schoolId,'rooms',r.id),{[`members.${u.studentId}.status`]:'playing'});return a},{maxAttempts:20})}
 if(op==='submit'){if(u.role!=='student')fail('สำหรับนักเรียนเท่านั้น');const attemptId=id.parse(p.attemptId);return db.runTransaction(async tx=>{const aRef=ref(u.schoolId,'attempts',attemptId),a=data(await tx.get(aRef));if(!a||a.studentId!==u.studentId)fail('ไม่ใช่การเล่นของคุณ','permission-denied');const r=await roomAccess(u,a.roomId,tx);if(r.roundId!==a.roundId)fail('รอบเปลี่ยนแล้ว ไม่รับคะแนนข้ามรอบ');const existing=data(await tx.get(ref(u.schoolId,'scores',attemptId)));if(existing)return clean(existing);if(!['ACTIVE','FINISHED'].includes(r.status))fail('ห้องยังไม่รับคะแนน');if(r.status==='FINISHED'&&Date.now()>Number((r as any).finishedAt||0)+120000)fail('หมดเวลารับงานหลังจบรอบ');const now=Date.now(),effectiveEnd=r.startsAt+r.pausedMs+r.timeLimit*1000;if(now>effectiveEnd+120000)fail('ส่งงานเกินเวลาที่อนุญาต');const seconds=Math.max(0,Math.round((Math.min(now,effectiveEnd)-a.startedAt-Math.max(0,r.pausedMs-a.pausedMs))/1000));let checked!:ReturnType<typeof replaySubmission>;try{checked=replaySubmission(r,p.submission as Submission,a.number,seconds)}catch(e){fail('โปรแกรมยังไม่ผ่าน: '+(e instanceof Error?e.message:'ตรวจคำสั่งอีกครั้ง'),'invalid-argument')}const result={id:attemptId,schoolId:u.schoolId,studentId:u.studentId,displayName:u.name,classId:a.classId,enrollmentId:a.enrollmentId,academicYear:a.academicYear,semester:a.semester,levelId:r.levelId,roomId:r.id,roundId:r.roundId,mode:r.mode,score:checked.score,stars:checked.stars,blocks:checked.blocks,attempts:checked.attempts,seconds,seed:r.seed,completedAt:now,verified:true};const bestRef=ref(u.schoolId,'progress',`${u.studentId}_${a.academicYear}_${a.semester}_${r.mode}_${r.levelId}`),best=data(await tx.get(bestRef)),rankRef=ref(u.schoolId,'room_rounds',r.roundId).collection('rankings').doc(u.studentId!),rank=data(await tx.get(rankRef));tx.create(ref(u.schoolId,'scores',attemptId),result);if(!best||compareResults(result,best)<0)tx.set(bestRef,result);if(!rank||compareResults(result,rank)<0)tx.set(rankRef,result);tx.update(aRef,{status:'verified',completedAt:stamp()});tx.update(ref(u.schoolId,'rooms',r.id),{[`members.${u.studentId}.status`]:'finished',updatedAt:stamp()});audit(tx,u,'score.verified',attemptId,{roomId:r.id,roundId:r.roundId});return result},{maxAttempts:20})}
 if(op==='rankings'){const r=await roomAccess(u,p.roomId);if(u.role==='student'&&!r.leaderboard)fail('ครูซ่อนอันดับไว้');return clean((await ref(u.schoolId,'room_rounds',r.roundId).collection('rankings').get()).docs.map(data).sort(compareResults).map(({studentCode,firstName,lastName,...v}:any)=>v))}
 if(op==='saveWorkspace'||op==='loadWorkspace'){if(u.role!=='student')fail('สำหรับนักเรียนเท่านั้น');if(op==='saveWorkspace'&&(!p.draft||JSON.stringify(p.draft).length>180000))fail('โปรแกรมใหญ่เกินไป');return db.runTransaction(async tx=>{const current=await tx.get(db.doc(`users/${u.uid}`)),student=await studentAccess(u,u.studentId!,tx);if(!current.data()?.active||student.status!=='active'||current.data()?.credentialVersion!==student.credentialVersion)fail('สิทธิ์หมดอายุ','permission-denied');const r=await roomAccess(u,p.roomId,tx),key=`${u.studentId}_${r.roundId}`,wRef=ref(u.schoolId,'workspaces',key);if(op==='loadWorkspace')return clean(data(await tx.get(wRef)));if(p.roundId!==r.roundId)fail('รอบเปลี่ยนแล้ว เก็บงานแยกจากรอบใหม่');const aId=p.draft.attempt?.id;let a:any=null;if(aId&&id.safeParse(aId).success)a=data(await tx.get(ref(u.schoolId,'attempts',aId)));tx.set(wRef,{studentId:u.studentId,schoolId:u.schoolId,roomId:r.id,roundId:r.roundId,levelId:r.levelId,seed:r.seed,classId:student.classId,academicYear:student.academicYear,semester:student.semester,draft:p.draft,updatedAt:stamp()});if(a&&a.studentId===u.studentId&&a.roundId===r.roundId){const blockUsage:Data={};let count=0;const walk=(cs:any[],depth=0)=>{if(depth>8)return;for(const c of cs){if(++count>200)return;if(['move','left','right','pick','drop','say','show','hide','repeat','broadcast','ending'].includes(c?.op))blockUsage[c.op]=(blockUsage[c.op]||0)+1;if(Array.isArray(c?.body))walk(c.body,depth+1)}};for(const cs of Object.values(p.draft.execution?.program||{}))if(Array.isArray(cs))walk(cs);tx.update(ref(u.schoolId,'attempts',aId),{hints:Math.min(3,Math.max(0,Number(p.draft.hints)||0)),blockUsage,errorCode:['collision','energy','key','item','program','mission'].includes(p.draft.errorCode)?p.draft.errorCode:'',telemetrySource:'client-reported'})}return{saved:true}})}
 if(op==='report'){staff(u);const reportClasses=await classes(u),allowed=reportClasses.map((c:any)=>c.id);if(p.classId&&!allowed.includes(p.classId))fail('ไม่มีสิทธิ์อ่านห้องนี้','permission-denied');const students=(await school(u.schoolId).collection('students').limit(2000).get()).docs.map(data),enrollments=(await school(u.schoolId).collection('enrollments').limit(10000).get()).docs.map(data),allScores=(await school(u.schoolId).collection('scores').limit(20000).get()).docs.map(data);const matching=(r:Data)=>allowed.includes(r.classId)&&(!p.classId||r.classId===p.classId)&&(!p.academicYear||r.academicYear===Number(p.academicYear))&&(!p.semester||r.semester===Number(p.semester));let rows=enrollments.filter(matching).map(e=>{const student=students.find(x=>x.id===e.studentId);return student?{...student,...{classId:e.classId,className:e.className||reportClasses.find((c:any)=>c.id===e.classId)?.className||student.className,academicYear:e.academicYear,semester:e.semester,studentNumber:e.studentNumber,enrollmentId:e.id,rowId:e.id}}:null}).filter(Boolean)as Data[];const grouped=new Map<string,Data>();for(const row of rows){const key=row.id+'_'+row.classId+'_'+row.academicYear+'_'+row.semester,previous=grouped.get(key);if(previous)previous.enrollmentIds.push(row.enrollmentId);else grouped.set(key,{...row,rowId:key,enrollmentIds:[row.enrollmentId]})}rows=[...grouped.values()];rows.sort((a,b)=>a.className.localeCompare(b.className,'th')||a.studentNumber-b.studentNumber);const total=rows.length,page=Math.max(1,Math.min(100,Number(p.page)||1));rows=rows.slice((page-1)*100,page*100);const enrollmentIds=new Set(rows.flatMap(r=>r.enrollmentIds)),best=new Map<string,Data>();for(const score of allScores.filter(s=>enrollmentIds.has(s.enrollmentId)&&matching(s)&&(!p.mode||s.mode===p.mode))){const key=score.studentId+'_'+score.classId+'_'+score.academicYear+'_'+score.semester+'_'+score.mode+'_'+score.levelId;if(!best.has(key)||compareResults(score,best.get(key))<0)best.set(key,score)}return clean({students:rows,scores:[...best.values()],total,page,pageSize:100,truncated:total>page*100})}
 if(op==='auditExport'){staff(u);if(p.classId)await classAccess(u,p.classId);await db.runTransaction(async tx=>audit(tx,u,'registry.exported',p.classId||'school',{count:Math.min(2000,Number(p.count)||0)}));return{logged:true}}
 if(op==='analytics'){staff(u);const allowed=(await classes(u)).map((c:any)=>c.id);if(p.classId&&!allowed.includes(p.classId))fail('ไม่มีสิทธิ์อ่านห้องนี้','permission-denied');const matching=(a:Data)=>allowed.includes(a.classId)&&(!p.classId||a.classId===p.classId)&&(!p.academicYear||a.academicYear===Number(p.academicYear))&&(!p.semester||a.semester===Number(p.semester))&&(!p.mode||a.mode===p.mode);const all=(await school(u.schoolId).collection('attempts').limit(20000).get()).docs.map(data).filter(matching),scores=(await school(u.schoolId).collection('scores').limit(20000).get()).docs.map(data).filter(matching);const custom=(await school(u.schoolId).collection('missions').get()).docs.map(data),levels=[...LEVELS.filter(l=>l.id),...custom.filter(m=>m.level.id>20).map(m=>m.level)].map(l=>{const attempts=all.filter(a=>a.levelId===l.id),done=scores.filter(s=>s.levelId===l.id);return{id:l.id,title:l.title,concept:l.concept,attempts:attempts.length,verified:done.length,hints:attempts.reduce((n,a)=>n+(a.hints||0),0),unfinished:attempts.filter(a=>a.status!=='verified').length,seconds:done.length?Math.round(done.reduce((n,s)=>n+s.seconds,0)/done.length):0,blocks:done.length?Math.round(done.reduce((n,s)=>n+s.blocks,0)/done.length):0}});const errors:Data={},blocks:Data={},stuck:Data[]=[];for(const a of all){if(a.errorCode)errors[a.errorCode]=(errors[a.errorCode]||0)+1;for(const [op,n]of Object.entries(a.blockUsage||{}))blocks[op]=(blocks[op]||0)+Number(n)}const students=(await school(u.schoolId).collection('students').limit(2000).get()).docs.map(data);for(const student of students.filter(s=>allowed.includes(s.classId))){const failed=levels.filter(l=>all.filter(a=>a.studentId===student.id&&a.levelId===l.id&&a.status!=='verified').length>=3&&!scores.some(s=>s.studentId===student.id&&s.levelId===l.id));if(failed.length)stuck.push({studentId:student.id,name:student.firstName+' '+student.lastName,levels:failed.map(l=>l.id)})}return{attempts:all.length,verified:all.filter(a=>a.status==='verified').length,unfinished:all.filter(a=>a.status!=='verified').length,levels,errors,blocks,stuck,mostFailed:[...levels].sort((a,b)=>b.unfinished-a.unfinished)[0]||null,telemetryNote:'คำใบ้ บล็อกที่ใช้ และข้อผิดพลาดเป็นข้อมูลจากเครื่องผู้เรียน ใช้วิเคราะห์ประกอบกับคะแนนที่เซิร์ฟเวอร์ตรวจ'}}
 if(op==='health'){staff(u,true);const logs=(await school(u.schoolId).collection('system_logs').orderBy('createdAt','desc').limit(100).get()).docs.map(data);const rooms=(await school(u.schoolId).collection('rooms').where('status','in',['WAITING','ACTIVE','PAUSED']).limit(200).get()).docs.map(data);return clean({version:'0.2.0',serverTime:Date.now(),activeRooms:rooms.length,onlinePlayers:rooms.reduce((n,r)=>n+Object.values(r.members).filter((m:any)=>Date.now()-m.lastSeen<60000).length,0),logs,metricsNote:'จำนวนผู้เล่นคำนวณจากสัญญาณใน 60 วินาที ไม่ใช่ยอดการเรียกเก็บเงินของ Firestore'})}
 fail('ไม่รองรับคำสั่งนี้','invalid-argument');
}
