import {safeCSV} from '../game/storage';
export const STUDENT_HEADERS=['รหัสนักเรียน','คำนำหน้า','ชื่อ','นามสกุล','ชื่อเล่น','ระดับชั้น','ห้อง','เลขที่','ปีการศึกษา','ภาคเรียน'];
export const STUDENT_FIELDS=['studentCode','prefix','firstName','lastName','nickname','grade','roomNumber','studentNumber','academicYear','semester'];
export function saveBlob(name:string,blob:Blob){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000)}
export async function exportTable(name:string,headers:string[],rows:unknown[][],format:'csv'|'xlsx'){
 if(format==='csv'){saveBlob(name+'.csv',new Blob(['\uFEFF'+[headers,...rows].map(row=>row.map(safeCSV).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));return}
 const Excel=await import('exceljs'),book=new Excel.Workbook(),sheet=book.addWorksheet('CODE QUEST');sheet.addRow(headers);for(const row of rows)sheet.addRow(row.map(v=>String(v??'')));sheet.views=[{state:'frozen',ySplit:1,xSplit:3}];sheet.columns.forEach(c=>{c.width=23;c.numFmt='@'});sheet.getRow(1).font={bold:true,color:{argb:'FFFFFFFF'}};sheet.getRow(1).fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF25826C'}};sheet.autoFilter={from:'A1',to:{row:rows.length+1,column:headers.length}};const buffer=await book.xlsx.writeBuffer();saveBlob(name+'.xlsx',new Blob([buffer as BlobPart],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}))
}
function parseCSV(input:string){const rows:string[][]=[];let row:string[]=[],field='',quoted=false;for(let i=0;i<input.length;i++){const c=input[i];if(c==='"'){if(quoted&&input[i+1]==='"'){field+='"';i++}else quoted=!quoted}else if(c===','&&!quoted){row.push(field);field=''}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&input[i+1]==='\n')i++;row.push(field);if(row.some(Boolean))rows.push(row);row=[];field=''}else field+=c}if(quoted)throw Error('CSV ปิดเครื่องหมายคำพูดไม่ครบ');row.push(field);if(row.some(Boolean))rows.push(row);return rows;}
export async function readStudentFile(file:File){if(file.size>5_000_000)throw Error('ไฟล์ต้องไม่เกิน 5 MB');let rows:string[][];
 if(file.name.toLowerCase().endsWith('.csv'))rows=parseCSV((await file.text()).replace(/^\uFEFF/,''));else if(file.name.toLowerCase().endsWith('.xlsx')){const Excel=await import('exceljs'),book=new Excel.Workbook();await book.xlsx.load(await file.arrayBuffer());const sheet=book.worksheets[0];if(!sheet)throw Error('ไฟล์ไม่มีแผ่นงาน');if(sheet.rowCount>1001||sheet.columnCount>50)throw Error('นำเข้าได้ไม่เกิน 1,000 แถวและ 50 คอลัมน์');rows=[];sheet.eachRow(r=>{const line:string[]=[];for(let i=1;i<=sheet.columnCount;i++){const cell=r.getCell(i);if(cell.type===Excel.ValueType.Formula)throw Error(`แถว ${r.number} มีสูตร กรุณาแปลงเป็นข้อความก่อน`);let value=cell.text;if(typeof cell.value==='number'&&/^0+$/.test(cell.numFmt||''))value=String(cell.value).padStart(cell.numFmt.length,'0');line.push(value.trim())}rows.push(line)})}else throw Error('รองรับเฉพาะ CSV และ Excel .xlsx');if(rows.length<2||rows.length>1001)throw Error('ไฟล์ต้องมีหัวตารางและรายชื่อ 1–1,000 คน');return{headers:rows[0],rows:rows.slice(1)};
}
