import {initializeApp,deleteApp,type FirebaseOptions} from 'firebase/app';
import {createUserWithEmailAndPassword,deleteUser,getAuth,signOut as signOutAuth,updateProfile,type Auth} from 'firebase/auth';
import {collection,deleteDoc,doc,getDoc,getDocs,limit,orderBy,query,runTransaction,serverTimestamp,setDoc,updateDoc,where,writeBatch,type Firestore,type QueryConstraint,Timestamp} from 'firebase/firestore';
import {z} from 'zod';
import {LEVELS,WORLDS,getLevel} from '../game/curriculum';
import {generateMap} from '../game/engine';
import {validateMission} from './mission-config';
import {compareResults,replaySubmission} from './replay';
import {DEFAULT_WEIGHTS,type Identity,type MissionSettings,type Room,type Submission} from './contracts';

type Data=Record<string,any>;
export type SparkDirectContext={db:Firestore;auth:Auth;config:any;firebaseOptions:FirebaseOptions};
const id=z.string().regex(/^[A-Za-z0-9_-]{1,128}$/),text=z.string().trim().min(1).max(120),opt=z.string().trim().max(120).default('');
const studentSchema=z.object({studentCode:text.max(40),prefix:opt,firstName:text,lastName:text,nickname:opt,classId:id,studentNumber:z.coerce.number().int().min(1).max(9999),status:z.enum(['active','inactive','graduated','transferred']).default('active')});
const enc=new TextEncoder();
const clean=(v:any):any=>v instanceof Timestamp?v.toMillis():Array.isArray(v)?v.map(clean):v&&typeof v==='object'&&!('toDate'in v)?Object.fromEntries(Object.entries(v).map(([k,x])=>[k,clean(x)])):v;
const schoolRef=(db:Firestore,sid:string)=>doc(db,'schools',sid),sub=(db:Firestore,sid:string,col:string,key:string)=>doc(db,'schools',sid,col,key),subcol=(db:Firestore,sid:string,col:string)=>collection(db,'schools',sid,col);
const randomId=()=>crypto.randomUUID(),randomInt=(a:number,b:number)=>a+Math.floor(crypto.getRandomValues(new Uint32Array(1))[0]/4294967296*(b-a));
async function hash(v:string){const out=await crypto.subtle.digest('SHA-256',enc.encode(v));return [...new Uint8Array(out)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function read(ref:any){const s=await getDoc(ref);return s.exists()?clean({...s.data(),id:s.id}):null}
async function audit(c:SparkDirectContext,u:Identity,action:string,target:string,detail:Data={}){await setDoc(sub(c.db,u.schoolId,'system_logs',randomId()),{action,target,actor:u.uid,role:u.role,schoolId:u.schoolId,detail,createdAt:serverTimestamp()})}
const defaults=(levelId:number):MissionSettings=>({level:structuredClone(getLevel(levelId)),active:true,energy:false,startEnergy:40,costs:{move:1,turn:1,pick:2,drop:2},weights:{...DEFAULT_WEIGHTS}});
function fail(message:string):never{throw Error(message)}
async function identity(c:SparkDirectContext):Promise<Identity>{const uid=c.auth.currentUser?.uid;if(!uid)fail('กรุณาเข้าสู่ระบบ');const u=await read(doc(c.db,'users',uid));if(!u||!u.active)fail('บัญชีนี้ยังไม่ได้รับสิทธิ์ หรือถูกปิดใช้งาน');if(u.role==='student'){const s=await read(sub(c.db,u.schoolId,'students',u.studentId));if(!s||s.status!=='active'||s.credentialVersion!==u.credentialVersion)fail('สิทธิ์นักเรียนหมดอายุ กรุณาเข้าสู่ระบบใหม่')}return{...u,uid}as Identity}
function staff(u:Identity,admin=false){if(!['admin','teacher'].includes(u.role)||(admin&&u.role!=='admin'))fail('ไม่มีสิทธิ์ทำรายการนี้')}
async function classAccess(c:SparkDirectContext,u:Identity,classId:string){const d=await read(sub(c.db,u.schoolId,'classes',id.parse(classId)));if(!d||d.status!=='active'||(u.role!=='admin'&&!d.teacherIds?.includes(u.uid)))fail('ไม่มีสิทธิ์จัดการห้องเรียนนี้');return d}
async function classes(c:SparkDirectContext,u:Identity){staff(u);const docs=await getDocs(query(subcol(c.db,u.schoolId,'classes'),limit(500)));return docs.docs.map(d=>clean({...d.data(),id:d.id})).filter((x:any)=>u.role==='admin'||x.teacherIds?.includes(u.uid))}
async function studentAccess(c:SparkDirectContext,u:Identity,studentId:string){const s=await read(sub(c.db,u.schoolId,'students',id.parse(studentId)));if(!s)fail('ไม่พบนักเรียน');if(u.role==='student'){if(u.studentId!==studentId)fail('ไม่มีสิทธิ์อ่านนักเรียนคนอื่น')}else if(u.role!=='admin'){await classAccess(c,u,s.classId)}return s}
async function listStudents(c:SparkDirectContext,u:Identity,p:Data){staff(u);const cs=await classes(c,u),allowed=cs.map((x:any)=>x.id);if(p.classId&&!allowed.includes(p.classId))fail('ไม่มีสิทธิ์อ่านห้องนี้');const q=await getDocs(query(subcol(c.db,u.schoolId,'students'),limit(2000)));let rows=q.docs.map(d=>clean({...d.data(),id:d.id})).filter((s:any)=>u.role==='admin'||allowed.includes(s.classId));if(p.classId)rows=rows.filter((s:any)=>s.classId===p.classId);if(p.status)rows=rows.filter((s:any)=>s.status===p.status);if(p.academicYear)rows=rows.filter((s:any)=>s.academicYear===Number(p.academicYear));if(p.semester)rows=rows.filter((s:any)=>s.semester===Number(p.semester));if(p.grade)rows=rows.filter((s:any)=>cs.find((x:any)=>x.id===s.classId)?.grade===p.grade);if(p.search){const k=String(p.search).trim().toLocaleLowerCase();rows=rows.filter((s:any)=>[s.studentCode,s.firstName,s.lastName,s.nickname].join(' ').toLocaleLowerCase().includes(k))}rows.sort((a:any,b:any)=>p.sort==='name'?a.firstName.localeCompare(b.firstName,'th'):p.sort==='code'?a.studentCode.localeCompare(b.studentCode):a.studentNumber-b.studentNumber||a.studentCode.localeCompare(b.studentCode));const page=Math.max(1,Math.min(100,Number(p.page)||1)),size=Math.min(100,Math.max(1,Number(p.pageSize)||25));return{rows:rows.slice((page-1)*size,page*size).map(({credentialVersion,...s}:any)=>s),total:rows.length,page,pageSize:size}}
async function allStudents(c:SparkDirectContext,u:Identity){const q=await getDocs(query(subcol(c.db,u.schoolId,'students'),limit(2000)));return q.docs.map(d=>clean({...d.data(),id:d.id}))}
async function upsertStudent(c:SparkDirectContext,u:Identity,input:Data,options:{dry?:boolean;mode?:string}={}){staff(u);const v=studentSchema.parse(input),code=v.studentCode.toUpperCase(),room=await classAccess(c,u,v.classId),all=await allStudents(c,u);let sid=input.id?id.parse(input.id):all.find((s:any)=>s.studentCode===code)?.id;const old=sid?all.find((s:any)=>s.id===sid):null;if(input.id&&all.some((s:any)=>s.studentCode===code&&s.id!==input.id))fail('รหัสนักเรียนซ้ำ');if(old&&!input.id&&!options.dry&&!options.mode)fail('มีรหัสนักเรียนนี้แล้ว ให้เปิดแก้ไขจากรายชื่อ');if(old&&input.revision!==undefined&&input.revision!==old.revision)fail('ข้อมูลถูกแก้ไขโดยผู้ใช้อื่น กรุณาโหลดใหม่');if(all.some((s:any)=>s.id!==sid&&s.status==='active'&&v.status==='active'&&s.classId===v.classId&&Number(s.studentNumber)===Number(v.studentNumber)))fail('เลขที่ซ้ำในห้องเรียน');sid=sid||randomId();if(options.dry)return{action:old?'existing':'new',studentId:sid};if(old&&options.mode==='skip')return{action:'skipped',studentId:sid};const changed=!old||old.classId!==v.classId||old.studentNumber!==v.studentNumber||old.status!==v.status,enrollmentId=changed?randomId():old.enrollmentId;const credential=old?await read(sub(c.db,u.schoolId,'student_credentials',sid)):null;const batch=writeBatch(c.db);const record={...v,studentCode:code,schoolId:u.schoolId,className:room.className,academicYear:room.academicYear,semester:room.semester,classIds:Array.from(new Set([...(old?.classIds||[]),v.classId])),enrollmentId,credentialVersion:old?.credentialVersion||0,revision:(old?.revision||0)+1,createdAt:old?.createdAt||Date.now(),createdBy:old?.createdBy||u.uid,updatedAt:serverTimestamp(),updatedBy:u.uid};batch.set(sub(c.db,u.schoolId,'students',sid),record);const key=await hash(code);batch.set(sub(c.db,u.schoolId,'student_code_keys',key),{studentId:sid});if(old&&old.studentCode!==code)batch.delete(sub(c.db,u.schoolId,'student_code_keys',await hash(old.studentCode)));if(changed){if(old?.enrollmentId)batch.set(sub(c.db,u.schoolId,'enrollments',old.enrollmentId),{status:'ended',endedAt:serverTimestamp(),updatedBy:u.uid},{merge:true});batch.set(sub(c.db,u.schoolId,'enrollments',enrollmentId),{schoolId:u.schoolId,studentId:sid,classId:v.classId,className:room.className,academicYear:room.academicYear,semester:room.semester,studentNumber:v.studentNumber,status:v.status==='active'?'active':'ended',enrolledAt:serverTimestamp(),endedAt:v.status==='active'?null:serverTimestamp(),createdBy:u.uid})}if(credential?.currentJoinKey&&old?.studentCode!==code)batch.set(doc(c.db,'student_join_keys',credential.currentJoinKey),{studentCode:code},{merge:true});batch.set(sub(c.db,u.schoolId,'system_logs',randomId()),{action:old?(old.classId!==v.classId?'student.transferred':'student.updated'):'student.created',target:sid,actor:u.uid,role:u.role,schoolId:u.schoolId,detail:{classId:v.classId,status:v.status},createdAt:serverTimestamp()});await batch.commit();return{action:old?'updated':'created',studentId:sid}}
async function roomAccess(c:SparkDirectContext,u:Identity,roomId:string){const r=await read(sub(c.db,u.schoolId,'rooms',id.parse(roomId)));if(!r)fail('ไม่พบห้องเกม');if(u.role==='student'){if(!r.members?.[u.studentId!])fail('คุณไม่ได้เข้าห้องนี้');const s=await studentAccess(c,u,u.studentId!);if(!r.classIds.includes(s.classId)||s.status!=='active')fail('สิทธิ์เข้าเรียนเปลี่ยนแปลง กรุณาติดต่อครู')}else{staff(u);for(const classId of r.classIds)await classAccess(c,u,classId)}return r as Room}
async function createTeacher(c:SparkDirectContext,u:Identity,v:any){const name='cq-teacher-'+randomId();const app=initializeApp(c.firebaseOptions,name),auth=getAuth(app);let created:any;try{created=await createUserWithEmailAndPassword(auth,v.email,v.password);if(auth.currentUser)await updateProfile(auth.currentUser,{displayName:v.name});try{await setDoc(doc(c.db,'users',created.user.uid),{schoolId:u.schoolId,role:'teacher',name:v.name,email:v.email,active:v.active,createdAt:serverTimestamp(),createdBy:u.uid})}catch(e){if(auth.currentUser)await deleteUser(auth.currentUser).catch(()=>{});throw e}await signOutAuth(auth).catch(()=>{});return created.user.uid}finally{await deleteApp(app).catch(()=>{})}}
async function resetPin(c:SparkDirectContext,u:Identity,sid:string){staff(u);const s=await studentAccess(c,u,sid);let pin='',joinKey='';for(let i=0;i<20;i++){pin=String(randomInt(100000,1000000));joinKey=await hash(`${u.schoolId}:${pin}`);if(!(await getDoc(doc(c.db,'student_join_keys',joinKey))).exists())break}if(!pin||!joinKey)fail('สร้าง PIN ไม่สำเร็จ กรุณาลองใหม่');const old=await read(sub(c.db,u.schoolId,'student_credentials',sid)),version=(s.credentialVersion||0)+1,cacheKey=btoa(String.fromCharCode(...crypto.getRandomValues(new Uint8Array(32))));const batch=writeBatch(c.db);if(old?.currentJoinKey)batch.delete(doc(c.db,'student_join_keys',old.currentJoinKey));batch.set(doc(c.db,'student_join_keys',joinKey),{schoolId:u.schoolId,studentId:sid,studentCode:s.studentCode,version,createdAt:serverTimestamp()});batch.set(sub(c.db,u.schoolId,'student_credentials',sid),{currentJoinKey:joinKey,version,updatedAt:serverTimestamp(),updatedBy:u.uid});batch.set(sub(c.db,u.schoolId,'student_cache_keys',sid),{cacheKey,version,updatedAt:serverTimestamp()});batch.update(sub(c.db,u.schoolId,'students',sid),{credentialVersion:version,updatedAt:serverTimestamp()});batch.set(sub(c.db,u.schoolId,'system_logs',randomId()),{action:'student.pin_reset',target:sid,actor:u.uid,role:u.role,schoolId:u.schoolId,createdAt:serverTimestamp()});await batch.commit();return{pin}}
async function join(c:SparkDirectContext,p:Data){const uid=c.auth.currentUser?.uid;if(!uid)fail('กรุณาเข้าสู่ระบบ');const code=String(p.code||'');if(!/^\d{6}$/.test(code))fail('รหัสห้องต้องเป็นตัวเลข 6 หลัก');const studentCode=String(p.studentCode||'').trim().toUpperCase(),pin=String(p.pin||'');if(!/^\d{6}$/.test(pin)||!studentCode)fail('ข้อมูลเข้าห้องไม่ถูกต้อง');const loc=await read(doc(c.db,'room_codes',code));if(!loc)fail('ข้อมูลเข้าห้องไม่ถูกต้อง');const joinKey=await hash(`${loc.schoolId}:${pin}`),ticket=await read(doc(c.db,'student_join_keys',joinKey));if(!ticket||ticket.schoolId!==loc.schoolId||ticket.studentCode!==studentCode)fail('ข้อมูลเข้าห้องไม่ถูกต้อง');const current=await read(doc(c.db,'users',uid));if(current&&(current.role!=='student'||current.studentId!==ticket.studentId||current.schoolId!==loc.schoolId))fail('ออกจากระบบก่อนเปลี่ยนนักเรียน');if(!current)await setDoc(doc(c.db,'users',uid),{uid,schoolId:loc.schoolId,studentId:ticket.studentId,role:'student',name:'นักเรียน',active:true,credentialVersion:ticket.version,joinKey,updatedAt:serverTimestamp()});else await updateDoc(doc(c.db,'users',uid),{credentialVersion:ticket.version,joinKey,updatedAt:serverTimestamp()});const s=await read(sub(c.db,loc.schoolId,'students',ticket.studentId)),room=await read(sub(c.db,loc.schoolId,'rooms',loc.roomId));if(!s||s.status!=='active'||s.credentialVersion!==ticket.version||!room||room.status==='CLOSED'||room.expiresAt<Date.now()||!room.classIds.includes(s.classId))fail('ไม่สามารถเข้าห้องนี้ได้');if(room.status!=='WAITING'){const eligible=await read(doc(c.db,'schools',loc.schoolId,'rooms',room.id,'eligible',s.id));if(!eligible||eligible.roundId!==room.roundId)fail('ไม่มีรายชื่อในรอบนี้')}const displayName=s.nickname||`นักสำรวจ ${s.studentNumber}`;await updateDoc(doc(c.db,'users',uid),{name:displayName,credentialVersion:ticket.version,updatedAt:serverTimestamp()});await runTransaction(c.db,async tx=>{const rr=sub(c.db,loc.schoolId,'rooms',room.id),snap=await tx.get(rr);if(!snap.exists())fail('ไม่พบห้องเกม');const r=clean({...snap.data(),id:snap.id}),existing=r.members?.[s.id];if(!existing&&(r.locked||r.status!=='WAITING'))fail('ครูล็อกห้องแล้ว');if(!existing&&r.memberCount>=40)fail('ห้องเต็มแล้ว (40 คน)');tx.set(sub(c.db,loc.schoolId,'room_members',`${r.id}_${s.id}`),{schoolId:loc.schoolId,roomId:r.id,studentId:s.id,enrollmentId:s.enrollmentId,classId:s.classId,joinedAt:serverTimestamp()},{merge:true});tx.update(rr,{[`members.${s.id}`]:{displayName,status:existing?.status||'waiting',lastSeen:Date.now()},memberCount:r.memberCount+(existing?0:1),updatedAt:serverTimestamp()})});return{identity:{uid,schoolId:loc.schoolId,studentId:s.id,role:'student',name:displayName,active:true,credentialVersion:ticket.version},roomId:room.id}}
async function getMany(c:SparkDirectContext,sid:string,colName:string,constraints:QueryConstraint[]=[]){const snap=await getDocs(query(subcol(c.db,sid,colName),...constraints));return snap.docs.map(d=>clean({...d.data(),id:d.id}))}
async function assetRows(c:SparkDirectContext,u:Identity){const configured=Array.isArray(c.config.assets)?c.config.assets:[];const settings=await getMany(c,u.schoolId,'asset_settings',[limit(200)]).catch(()=>[]);return configured.map((a:any)=>({...a,active:settings.find((s:any)=>s.id===a.id)?.active??a.active!==false,bytes:Number(a.bytes||0),digest:String(a.digest||'github-static')}))}
export async function sparkCall<T=any>(c:SparkDirectContext,op:string,p:Data={}):Promise<T>{
 if(op==='join')return await join(c,p) as T;
 const u=await identity(c);
 if(op==='me'){const own=u.role==='student'?await studentAccess(c,u,u.studentId!):null,cache=u.role==='student'?await read(sub(c.db,u.schoolId,'student_cache_keys',u.studentId!)):null;return clean({identity:u,student:own,cacheKey:cache?.cacheKey||null,school:await read(schoolRef(c.db,u.schoolId)),backendMode:'spark-direct'}) as T}
 if(op==='classes')return await classes(c,u) as T;
 if(op==='students')return await listStudents(c,u,p) as T;
 if(op==='saveStudent')return await upsertStudent(c,u,p) as T;
 if(op==='studentDetail'){const s=await studentAccess(c,u,p.studentId),scores=(await getMany(c,u.schoolId,'scores',[where('studentId','==',s.id),limit(500)])).sort((a:any,b:any)=>Number(b.completedAt)-Number(a.completedAt)),enrollments=await getMany(c,u.schoolId,'enrollments',[where('studentId','==',s.id),limit(100)]);return{student:s,scores,enrollments} as T}
 if(op==='import'){staff(u);const rows=Array.isArray(p.rows)?p.rows:[];if(!rows.length||rows.length>25)fail('นำเข้าได้ครั้งละ 1–25 แถว');const out=[];const codes=new Set<string>(),numbers=new Set<string>();for(const row of rows){try{const code=String(row.student?.studentCode||'').trim().toUpperCase(),n=`${row.student?.classId}:${row.student?.studentNumber}`;if(codes.has(code)||numbers.has(n))fail('รหัสหรือเลขที่ซ้ำในชุดข้อมูล');codes.add(code);numbers.add(n);out.push({rowId:row.rowId,ok:true,...await upsertStudent(c,u,row.student,{dry:!!p.preview,mode:p.mode==='update'?'update':'skip'})})}catch(e){out.push({rowId:row.rowId,ok:false,error:e instanceof Error?e.message:'บันทึกไม่สำเร็จ'})}}return out as T}
 if(op==='saveClass'){staff(u,true);const v=z.object({id:id.optional(),className:text,grade:text,roomNumber:text,academicYear:z.coerce.number().int().min(2500).max(2700),semester:z.coerce.number().int().min(1).max(3),teacherIds:z.array(id).max(20),status:z.enum(['active','inactive'])}).parse(p);for(const tid of v.teacherIds){const teacher=await read(doc(c.db,'users',tid));if(!teacher||teacher.schoolId!==u.schoolId||!['teacher','admin'].includes(teacher.role)||!teacher.active)fail('ครูที่เลือกไม่มีสิทธิ์ในโรงเรียนนี้')}const classId=v.id||randomId(),old=await read(sub(c.db,u.schoolId,'classes',classId));if(old&&(old.academicYear!==v.academicYear||old.semester!==v.semester))fail('สร้างห้องใหม่เมื่อต้องเปลี่ยนปีหรือภาคเรียน เพื่อเก็บบริบทประวัติเดิม');await setDoc(sub(c.db,u.schoolId,'classes',classId),{...v,id:classId,schoolId:u.schoolId,createdAt:old?.createdAt||Date.now(),createdBy:old?.createdBy||u.uid,updatedAt:serverTimestamp(),updatedBy:u.uid});await audit(c,u,'class.saved',classId);return{id:classId} as T}
 if(op==='teachers'){staff(u,true);const snap=await getDocs(query(collection(c.db,'users'),where('schoolId','==',u.schoolId),limit(200)));return snap.docs.map(d=>clean({...d.data(),id:d.id})).filter((x:any)=>['teacher','admin'].includes(x.role)) as T}
 if(op==='saveTeacher'){staff(u,true);const v=z.object({id:id.optional(),name:text,email:z.string().email().max(200),password:z.string().min(12).max(128).optional(),active:z.boolean()}).parse(p);let target=v.id;if(!target){if(!v.password)fail('กำหนดรหัสผ่านอย่างน้อย 12 ตัว');target=await createTeacher(c,u,v)}else{const old=await read(doc(c.db,'users',target));if(!old||old.schoolId!==u.schoolId||old.role!=='teacher')fail('แก้ไขบัญชีนี้ไม่ได้');if(v.email!==old.email)fail('โหมด Spark ฟรียังไม่เปลี่ยนอีเมล Firebase Auth จากหน้าเว็บ กรุณาสร้างบัญชีใหม่แทน');await updateDoc(doc(c.db,'users',target),{name:v.name,active:v.active,updatedAt:serverTimestamp(),updatedBy:u.uid})}await audit(c,u,'teacher.saved',target!);return{id:target,note:'Spark mode: การปิดบัญชีบังคับด้วย Firestore Rules ไม่ได้ disable ใน Firebase Auth'} as T}
 if(op==='resetPin')return await resetPin(c,u,id.parse(p.studentId)) as T;
 if(op==='worlds'){staff(u);const saved=await getMany(c,u.schoolId,'worlds',[limit(20)]);return WORLDS.map(w=>({...w,...saved.find((s:any)=>Number(s.id)===w.id),id:w.id})) as T}
 if(op==='saveWorld'){staff(u,true);const v=z.object({id:z.number().int().min(1).max(3),name:text,sub:text}).parse(p);await setDoc(sub(c.db,u.schoolId,'worlds',String(v.id)),{name:v.name,sub:v.sub,updatedAt:serverTimestamp()});await audit(c,u,'world.saved',String(v.id));return{saved:true} as T}
 if(op==='saveSettings'){staff(u,true);const v=z.object({name:text}).parse(p);await updateDoc(schoolRef(c.db,u.schoolId),v);await audit(c,u,'settings.saved',u.schoolId);return{saved:true} as T}
 if(op==='missions'){staff(u);const saved=await getMany(c,u.schoolId,'missions',[limit(1000)]);return [...LEVELS.map(l=>saved.find((m:any)=>m.level?.id===l.id)||defaults(l.id)),...saved.filter((m:any)=>m.level?.id>20)].sort((a:any,b:any)=>a.level.id-b.level.id) as T}
 if(op==='saveMission'){staff(u,true);let m:MissionSettings;try{m=validateMission(p)}catch(e){fail(e instanceof Error?e.message:'บทเรียนไม่ถูกต้อง')}if(m.level.assetId){const assets=await assetRows(c,u);if(!assets.find((a:any)=>a.id===m.level.assetId&&a.active))fail('โมเดลที่เลือกถูกปิดไว้หรือไม่พบ')}const levelId=m.level.id,ref=sub(c.db,u.schoolId,'missions',String(levelId)),old=await read(ref);if(p.create&&(old||levelId<=20))fail('รหัสด่านนี้มีอยู่แล้ว');await setDoc(ref,{...m,updatedAt:serverTimestamp(),updatedBy:u.uid});await audit(c,u,'mission.saved',String(levelId));return{saved:true} as T}
 if(op==='assets'){const rows=await assetRows(c,u);return{ready:true,storageMode:'github',rows} as T}
 if(op==='uploadAsset')fail('โหมดฟรีใช้ GitHub Pages เก็บไฟล์ GLB กรุณาเพิ่มไฟล์ใน public/models และลงทะเบียนใน school-config.json');
 if(op==='setAssetActive'){staff(u,true);const assetId=id.parse(p.assetId);await setDoc(sub(c.db,u.schoolId,'asset_settings',assetId),{active:!!p.active,updatedAt:serverTimestamp(),updatedBy:u.uid});return{saved:true} as T}
 if(op==='loadAsset'){const rows=await assetRows(c,u),asset=rows.find((a:any)=>a.id===p.assetId&&a.active);if(!asset)fail('ไม่พบโมเดลนี้');return{url:asset.path||asset.url} as T}
 if(op==='rooms'){if(u.role==='student')fail('นักเรียนเข้าห้องด้วยรหัสห้องเท่านั้น');const allowed=(await classes(c,u)).map((x:any)=>x.id),rooms=await getMany(c,u.schoolId,'rooms',[limit(200)]);return rooms.filter((r:any)=>r.classIds.every((x:string)=>allowed.includes(x))).sort((a:any,b:any)=>b.expiresAt-a.expiresAt) as T}
 if(op==='createRoom'){staff(u);const v=z.object({name:text,classIds:z.array(id).min(1).max(5),levelId:z.coerce.number().int().min(1).max(999),mode:z.enum(['practice','challenge','assignment']),difficulty:z.enum(['easy','normal','hard']),timeLimit:z.coerce.number().int().min(60).max(86400),attemptLimit:z.coerce.number().int().min(1).max(100),hint:z.boolean(),leaderboard:z.boolean(),seed:z.string().regex(/^[A-Za-z0-9-]{1,64}$/).optional()}).parse(p);const cs=[] as Data[];for(const classId of v.classIds)cs.push(await classAccess(c,u,classId));if(cs.some(x=>x.academicYear!==cs[0].academicYear||x.semester!==cs[0].semester))fail('เลือกห้องในปีและภาคเรียนเดียวกัน');const savedMission=await read(sub(c.db,u.schoolId,'missions',String(v.levelId)));if(!savedMission&&v.levelId>20)fail('ไม่พบด่านนี้');const mission=savedMission||defaults(v.levelId);if(!mission.active)fail('ด่านนี้ถูกปิดไว้');let code='';for(let i=0;i<30;i++){const candidate=String(randomInt(100000,1000000));if(!(await getDoc(doc(c.db,'room_codes',candidate))).exists()){code=candidate;break}}if(!code)fail('สร้างรหัสห้องไม่สำเร็จ กรุณาลองใหม่');const roomId=randomId(),roundId=randomId(),seed=v.seed||`P4-L${v.levelId}-${randomInt(100000,999999999)}`;generateMap(mission.level,seed,v.difficulty);const worldData=await read(sub(c.db,u.schoolId,'worlds',String(mission.level.world))),world={...WORLDS[mission.level.world-1],...(worldData?{name:worldData.name,sub:worldData.sub}:{})};const room={...v,world,id:roomId,code,seed,schoolId:u.schoolId,teacherIds:Array.from(new Set(cs.flatMap(x=>x.teacherIds))),academicYear:cs[0].academicYear,semester:cs[0].semester,status:'WAITING',locked:false,roundId,round:1,mission,memberCount:0,members:{},startsAt:0,pausedAt:0,pausedMs:0,expiresAt:Date.now()+7*86400000,createdBy:u.uid,createdAt:serverTimestamp(),updatedAt:serverTimestamp()};const batch=writeBatch(c.db);batch.set(sub(c.db,u.schoolId,'rooms',roomId),room);batch.set(doc(c.db,'room_codes',code),{schoolId:u.schoolId,roomId});batch.set(sub(c.db,u.schoolId,'system_logs',randomId()),{action:'room.created',target:roomId,actor:u.uid,role:u.role,schoolId:u.schoolId,createdAt:serverTimestamp()});await batch.commit();return clean({...room,createdAt:Date.now(),updatedAt:Date.now()}) as T}
 if(op==='room')return await roomAccess(c,u,p.roomId) as T;
 if(op==='controlRoom'){staff(u);const action=z.enum(['start','pause','resume','end','new','close','lock','unlock','hintOn','hintOff','show','hide']).parse(p.action),r=await roomAccess(c,u,id.parse(p.roomId)),now=Date.now(),patch:Data={updatedAt:serverTimestamp()};let eligible:Data[]=[];if(action==='start'){if(r.status!=='WAITING'||!r.memberCount)fail('เริ่มได้เมื่อมีนักเรียนในห้องรอ');eligible=(await allStudents(c,u)).filter((s:any)=>s.status==='active'&&r.classIds.includes(s.classId));if(eligible.length>450)fail('รายชื่อที่อนุญาตเกิน 450 คน เลือกห้องเรียนน้อยลง');Object.assign(patch,{status:'ACTIVE',locked:true,startsAt:now+3000,pausedMs:0,pausedAt:0})}if(action==='pause'){if(r.status!=='ACTIVE')fail('พักได้เฉพาะห้องที่กำลังเล่น');Object.assign(patch,{status:'PAUSED',pausedAt:now})}if(action==='resume'){if(r.status!=='PAUSED')fail('ห้องไม่ได้พักอยู่');Object.assign(patch,{status:'ACTIVE',pausedMs:r.pausedMs+now-r.pausedAt,pausedAt:0})}if(action==='end'){if(!['ACTIVE','PAUSED'].includes(r.status))fail('รอบนี้ไม่ได้กำลังเล่น');Object.assign(patch,{status:'FINISHED',finishedAt:now})}if(action==='close')patch.status='CLOSED';if(action==='new'){if(!['FINISHED','WAITING'].includes(r.status))fail('จบรอบก่อนเริ่มรอบใหม่');Object.assign(patch,{status:'WAITING',locked:false,round:r.round+1,roundId:randomId(),seed:`P4-L${r.levelId}-${randomInt(100000,999999999)}`,startsAt:0,pausedAt:0,pausedMs:0,members:Object.fromEntries(Object.entries(r.members).map(([k,v]:any)=>[k,{...v,status:'waiting'}]))})}if(action==='lock'||action==='unlock')patch.locked=action==='lock';if(action==='hintOn'||action==='hintOff')patch.hint=action==='hintOn';if(action==='show'||action==='hide')patch.leaderboard=action==='show';const batch=writeBatch(c.db);if(action==='start'){for(const s of eligible)batch.set(doc(c.db,'schools',u.schoolId,'rooms',r.id,'eligible',s.id),{studentId:s.id,enrollmentId:s.enrollmentId,classId:s.classId,roundId:r.roundId,academicYear:s.academicYear,semester:s.semester,studentNumber:s.studentNumber});batch.set(sub(c.db,u.schoolId,'room_rounds',r.roundId),{...r,...patch,eligibleIds:eligible.map(s=>s.id),createdAt:serverTimestamp()})}if(action==='end'||action==='close')batch.set(sub(c.db,u.schoolId,'room_rounds',r.roundId),{status:patch.status,finishedAt:now},{merge:true});batch.update(sub(c.db,u.schoolId,'rooms',r.id),patch);batch.set(sub(c.db,u.schoolId,'system_logs',randomId()),{action:`room.${action}`,target:r.id,actor:u.uid,role:u.role,schoolId:u.schoolId,detail:{roundId:r.roundId},createdAt:serverTimestamp()});await batch.commit();return{saved:true} as T}
 if(op==='heartbeat'){if(u.role!=='student')fail('สำหรับนักเรียนเท่านั้น');const r=await roomAccess(c,u,p.roomId),old=r.members[u.studentId!];if(Date.now()-old.lastSeen>15000)await updateDoc(sub(c.db,u.schoolId,'rooms',r.id),{[`members.${u.studentId}.lastSeen`]:Date.now(),updatedAt:serverTimestamp()});return{online:true} as T}
 if(op==='startAttempt'){if(u.role!=='student')fail('สำหรับนักเรียนเท่านั้น');const requestId=id.parse(p.requestId),r=await roomAccess(c,u,p.roomId),attemptId=await hash(`${u.studentId}:${r.roundId}:${requestId}`);return await runTransaction(c.db,async tx=>{const aRef=sub(c.db,u.schoolId,'attempts',attemptId),aSnap=await tx.get(aRef);if(aSnap.exists())return clean({...aSnap.data(),id:aSnap.id});const roomSnap=await tx.get(sub(c.db,u.schoolId,'rooms',r.id));if(!roomSnap.exists())fail('ไม่พบห้องเกม');const room=clean({...roomSnap.data(),id:roomSnap.id}) as Room,now=Date.now();if(room.status!=='ACTIVE'||now<room.startsAt)fail('รอครูเริ่มหรือกลับมาเล่นต่อ');if(now-room.startsAt-room.pausedMs>room.timeLimit*1000)fail('หมดเวลารอบนี้แล้ว');const eligibleRef=doc(c.db,'schools',u.schoolId,'rooms',r.id,'eligible',u.studentId!),eligibleSnap=await tx.get(eligibleRef);if(!eligibleSnap.exists()||eligibleSnap.data().roundId!==room.roundId)fail('ไม่มีสิทธิ์ในรอบนี้');const memberRef=sub(c.db,u.schoolId,'round_players',`${room.roundId}_${u.studentId}`),memberSnap=await tx.get(memberRef),number=Number(memberSnap.data()?.attempts||0)+1;if(number>room.attemptLimit)fail('ครบจำนวนครั้งที่ครูกำหนด');const eligible=eligibleSnap.data(),a={id:attemptId,levelId:room.levelId,schoolId:u.schoolId,studentId:u.studentId,roomId:room.id,roundId:room.roundId,mode:room.mode,number,startedAt:now,pausedMs:room.pausedMs,status:'started',classId:eligible.classId,enrollmentId:eligible.enrollmentId,academicYear:eligible.academicYear,semester:eligible.semester};tx.set(aRef,a);tx.set(memberRef,{studentId:u.studentId,roomId:room.id,roundId:room.roundId,attempts:number,activeAttempt:aRef.id},{merge:true});tx.update(sub(c.db,u.schoolId,'rooms',room.id),{[`members.${u.studentId}.status`]:'playing',updatedAt:serverTimestamp()});return a}) as T}
 if(op==='submit'){if(u.role!=='student')fail('สำหรับนักเรียนเท่านั้น');const attemptId=id.parse(p.attemptId),a=await read(sub(c.db,u.schoolId,'attempts',attemptId));if(!a||a.studentId!==u.studentId)fail('ไม่ใช่การเล่นของคุณ');const r=await roomAccess(c,u,a.roomId);if(r.roundId!==a.roundId)fail('รอบเปลี่ยนแล้ว ไม่รับคะแนนข้ามรอบ');const existing=await read(sub(c.db,u.schoolId,'scores',attemptId));if(existing)return existing as T;if(!['ACTIVE','FINISHED'].includes(r.status))fail('ห้องยังไม่รับคะแนน');const now=Date.now(),effectiveEnd=r.startsAt+r.pausedMs+r.timeLimit*1000;if(now>effectiveEnd+120000)fail('ส่งงานเกินเวลาที่อนุญาต');const seconds=Math.max(0,Math.round((Math.min(now,effectiveEnd)-a.startedAt-Math.max(0,r.pausedMs-a.pausedMs))/1000));let checked;try{checked=replaySubmission(r,p.submission as Submission,a.number,seconds)}catch(e){fail('โปรแกรมยังไม่ผ่าน: '+(e instanceof Error?e.message:'ตรวจคำสั่งอีกครั้ง'))}const result={id:attemptId,schoolId:u.schoolId,studentId:u.studentId,displayName:u.name,classId:a.classId,enrollmentId:a.enrollmentId,academicYear:a.academicYear,semester:a.semester,levelId:r.levelId,roomId:r.id,roundId:r.roundId,mode:r.mode,score:checked.score,stars:checked.stars,blocks:checked.blocks,attempts:checked.attempts,seconds,seed:r.seed,completedAt:now,verified:false,verification:'client-rule-checked' as const};await runTransaction(c.db,async tx=>{const scoreRef=sub(c.db,u.schoolId,'scores',attemptId),scoreSnap=await tx.get(scoreRef);if(scoreSnap.exists())return;const progressRef=sub(c.db,u.schoolId,'progress',`${u.studentId}_${a.academicYear}_${a.semester}_${r.mode}_${r.levelId}`),rankRef=doc(c.db,'schools',u.schoolId,'room_rounds',r.roundId,'rankings',u.studentId!),best=await tx.get(progressRef),rank=await tx.get(rankRef);tx.set(scoreRef,result);if(!best.exists()||compareResults(result,clean({...best.data(),id:best.id}))<0)tx.set(progressRef,result);if(!rank.exists()||compareResults(result,clean({...rank.data(),id:rank.id}))<0)tx.set(rankRef,result);tx.update(sub(c.db,u.schoolId,'attempts',attemptId),{status:'client-checked',completedAt:serverTimestamp()});tx.update(sub(c.db,u.schoolId,'rooms',r.id),{[`members.${u.studentId}.status`]:'finished',updatedAt:serverTimestamp()})});return result as T}
 if(op==='rankings'){const r=await roomAccess(c,u,p.roomId);if(u.role==='student'&&!r.leaderboard)fail('ครูซ่อนอันดับไว้');const rows=await getDocs(collection(c.db,'schools',u.schoolId,'room_rounds',r.roundId,'rankings'));return rows.docs.map(d=>clean({...d.data(),id:d.id})).sort(compareResults) as T}
 if(op==='saveWorkspace'||op==='loadWorkspace'){if(u.role!=='student')fail('สำหรับนักเรียนเท่านั้น');const r=await roomAccess(c,u,p.roomId),key=`${u.studentId}_${r.roundId}`,wRef=sub(c.db,u.schoolId,'workspaces',key);if(op==='loadWorkspace')return await read(wRef) as T;if(!p.draft||JSON.stringify(p.draft).length>180000)fail('โปรแกรมใหญ่เกินไป');if(p.roundId!==r.roundId)fail('รอบเปลี่ยนแล้ว เก็บงานแยกจากรอบใหม่');const student=await studentAccess(c,u,u.studentId!);await setDoc(wRef,{studentId:u.studentId,schoolId:u.schoolId,roomId:r.id,roundId:r.roundId,levelId:r.levelId,seed:r.seed,classId:student.classId,academicYear:student.academicYear,semester:student.semester,draft:p.draft,updatedAt:serverTimestamp()});return{saved:true} as T}
 if(op==='report'){staff(u);const reportClasses=await classes(c,u),allowed=reportClasses.map((x:any)=>x.id);if(p.classId&&!allowed.includes(p.classId))fail('ไม่มีสิทธิ์อ่านห้องนี้');const students=await getMany(c,u.schoolId,'students',[limit(2000)]),enrollments=await getMany(c,u.schoolId,'enrollments',[limit(10000)]),allScores=await getMany(c,u.schoolId,'scores',[limit(20000)]),matching=(r:Data)=>allowed.includes(r.classId)&&(!p.classId||r.classId===p.classId)&&(!p.academicYear||r.academicYear===Number(p.academicYear))&&(!p.semester||r.semester===Number(p.semester));let rows=enrollments.filter(matching).map((e:any)=>{const student=students.find((x:any)=>x.id===e.studentId);return student?{...student,classId:e.classId,className:e.className||reportClasses.find((x:any)=>x.id===e.classId)?.className||student.className,academicYear:e.academicYear,semester:e.semester,studentNumber:e.studentNumber,enrollmentId:e.id,rowId:e.id}:null}).filter(Boolean) as Data[];const grouped=new Map<string,Data>();for(const row of rows){const key=row.id+'_'+row.classId+'_'+row.academicYear+'_'+row.semester,previous=grouped.get(key);if(previous)previous.enrollmentIds.push(row.enrollmentId);else grouped.set(key,{...row,rowId:key,enrollmentIds:[row.enrollmentId]})}rows=[...grouped.values()].sort((a,b)=>a.className.localeCompare(b.className,'th')||a.studentNumber-b.studentNumber);const total=rows.length,page=Math.max(1,Math.min(100,Number(p.page)||1));rows=rows.slice((page-1)*100,page*100);const enrollmentIds=new Set(rows.flatMap(r=>r.enrollmentIds)),best=new Map<string,Data>();for(const score of allScores.filter((s:any)=>enrollmentIds.has(s.enrollmentId)&&matching(s)&&(!p.mode||s.mode===p.mode))){const key=score.studentId+'_'+score.classId+'_'+score.academicYear+'_'+score.semester+'_'+score.mode+'_'+score.levelId;if(!best.has(key)||compareResults(score,best.get(key))<0)best.set(key,score)}return{students:rows,scores:[...best.values()],total,page,pageSize:100,truncated:total>page*100,verificationMode:'client'} as T}
 if(op==='auditExport'){staff(u);if(p.classId)await classAccess(c,u,p.classId);await audit(c,u,'registry.exported',p.classId||'school',{count:Math.min(2000,Number(p.count)||0)});return{logged:true} as T}
 if(op==='analytics'){staff(u);const allowed=(await classes(c,u)).map((x:any)=>x.id);if(p.classId&&!allowed.includes(p.classId))fail('ไม่มีสิทธิ์อ่านห้องนี้');const matching=(a:Data)=>allowed.includes(a.classId)&&(!p.classId||a.classId===p.classId)&&(!p.academicYear||a.academicYear===Number(p.academicYear))&&(!p.semester||a.semester===Number(p.semester))&&(!p.mode||a.mode===p.mode),all=(await getMany(c,u.schoolId,'attempts',[limit(20000)])).filter(matching),scores=(await getMany(c,u.schoolId,'scores',[limit(20000)])).filter(matching),custom=await getMany(c,u.schoolId,'missions',[limit(1000)]),levels=[...LEVELS.filter(l=>l.id),...custom.filter((m:any)=>m.level?.id>20).map((m:any)=>m.level)].map((l:any)=>{const attempts=all.filter((a:any)=>a.levelId===l.id),done=scores.filter((s:any)=>s.levelId===l.id);return{id:l.id,title:l.title,concept:l.concept,attempts:attempts.length,verified:done.length,hints:attempts.reduce((n:number,a:any)=>n+(a.hints||0),0),unfinished:attempts.filter((a:any)=>!['client-checked','verified'].includes(a.status)).length,seconds:done.length?Math.round(done.reduce((n:number,s:any)=>n+s.seconds,0)/done.length):0,blocks:done.length?Math.round(done.reduce((n:number,s:any)=>n+s.blocks,0)/done.length):0}}),errors:Data={},blocks:Data={},stuck:Data[]=[];for(const a of all){if(a.errorCode)errors[a.errorCode]=(errors[a.errorCode]||0)+1;for(const [name,n]of Object.entries(a.blockUsage||{}))blocks[name]=(blocks[name]||0)+Number(n)}const students=await getMany(c,u.schoolId,'students',[limit(2000)]);for(const student of students.filter((s:any)=>allowed.includes(s.classId))){const failed=levels.filter((l:any)=>all.filter((a:any)=>a.studentId===student.id&&a.levelId===l.id&&!['client-checked','verified'].includes(a.status)).length>=3&&!scores.some((s:any)=>s.studentId===student.id&&s.levelId===l.id));if(failed.length)stuck.push({studentId:student.id,name:student.firstName+' '+student.lastName,levels:failed.map((l:any)=>l.id)})}return{attempts:all.length,verified:scores.length,unfinished:all.filter((a:any)=>!['client-checked','verified'].includes(a.status)).length,levels,errors,blocks,stuck,mostFailed:[...levels].sort((a:any,b:any)=>b.unfinished-a.unfinished)[0]||null,telemetryNote:'โหมด Spark ฟรี: คะแนนตรวจซ้ำด้วยกติกาเกมบนอุปกรณ์ แล้ว Firestore Rules ตรวจสิทธิ์/โครงสร้าง ไม่ใช่การตรวจด้วยเซิร์ฟเวอร์ที่เชื่อถือได้'} as T}
 if(op==='health'){staff(u,true);let logs:Data[]=[];try{logs=await getMany(c,u.schoolId,'system_logs',[orderBy('createdAt','desc'),limit(100)])}catch{logs=await getMany(c,u.schoolId,'system_logs',[limit(100)])}const rooms=(await getMany(c,u.schoolId,'rooms',[limit(200)])).filter((r:any)=>['WAITING','ACTIVE','PAUSED'].includes(r.status));return{version:'0.3.0-spark-direct',serverTime:Date.now(),activeRooms:rooms.length,onlinePlayers:rooms.reduce((n:number,r:any)=>n+Object.values(r.members||{}).filter((m:any)=>Date.now()-m.lastSeen<60000).length,0),logs,metricsNote:'GitHub Pages + Firebase Spark · ไม่มี Cloud Functions/Storage และไม่มีค่าใช้จ่ายแบบ pay-as-you-go'} as T}
 fail('ไม่รองรับคำสั่งนี้');
}
