'use client';
import { forwardRef, useEffect, useImperativeHandle, useRef, useState } from 'react';
import type * as BlocklyType from 'blockly';
import type { Command, GameMap, Level, Op, Program } from '@/lib/game/types';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Puzzle, Undo2, Redo2, Trash2, Save, Code2, ZoomIn, ZoomOut } from 'lucide-react';
export type EditorHandle = { program: () => Program; save: () => object | null; load: (data:object) => void; reset: () => void; highlight: (id?:string) => void; insert: (op:Op) => void };
type Props = { level:Level; map:GameMap; saved:object|null; locked:boolean; onChange:(data:object, count:number)=>void; onSave:()=>void; onDelete:()=>void; onCode:()=>void; onError:(message:string)=>void; onReady:()=>void };
export const BLOCK_LABELS:Record<string,string>={move:'เดินหน้า 1 ช่อง',left:'เลี้ยวซ้าย 90°',right:'เลี้ยวขวา 90°',pick:'เก็บของ',drop:'วางของ',say:'พูด',repeat:'ทำซ้ำ',show:'แสดงตัว',hide:'ซ่อนตัว',broadcast:'ส่งสัญญาณ',ending:'จบเรื่อง'};
function blockJSON(commands:Command[]):object|undefined{if(!commands.length)return undefined;const [c,...rest]=commands;return {type:'cq_'+c.op,fields:{...(c.op==='repeat'?{TIMES:c.count||3}:{}),...(c.op==='say'?{TEXT:c.text||'สวัสดี!',ACTOR:c.actor||'bot'}:{})},...(c.body?.length?{inputs:{DO:{block:blockJSON(c.body)}}}:{}),...(rest.length?{next:{block:blockJSON(rest)}}:{})};}
export function initialWorkspace(level:Level,map:GameMap){let cs:Command[]=[{op:'move'}];if(level.id===9)cs=map.optimal.map(c=>c.op==='right'?{op:'left'}:c);if(level.id===19)cs=[{op:'repeat',count:2,body:[{op:'move'}]},{op:'right'},{op:'repeat',count:4,body:[{op:'move'}]}];if(level.kind==='story')cs=[];return {blocks:{languageVersion:0,blocks:[{type:'cq_start',x:32,y:35,...(cs.length?{next:{block:blockJSON(cs)}}:{})},...(level.id===15?[{type:'cq_key',x:32,y:130}]:[]),...(level.id===17?[{type:'cq_receive',x:32,y:200}]:[])]}};}
export function programWorkspace(p:Program){return {blocks:{languageVersion:0,blocks:Object.entries(p).filter(([k,cs])=>k==='start'||cs.length).map(([k,cs],i)=>({type:'cq_'+k,x:28+i*35,y:30+i*180,...(cs.length?{next:{block:blockJSON(cs)}}:{})}))}};}
function defineBlocks(B:typeof BlocklyType){if(B.Blocks['cq_start'])return;const defs:any[]=[];for(const [name,label]of Object.entries(BLOCK_LABELS)){if(name==='repeat'||name==='say')continue;defs.push({type:'cq_'+name,message0:label,previousStatement:null,nextStatement:null,colour:['move','left','right'].includes(name)?'#5a91d7':['broadcast','ending'].includes(name)?'#e5ad39':'#a080cb',tooltip:label});}defs.push({type:'cq_repeat',message0:'ทำซ้ำ %1 ครั้ง',args0:[{type:'field_number',name:'TIMES',value:3,min:1,max:20,precision:1}],message1:'%1',args1:[{type:'input_statement',name:'DO'}],previousStatement:null,nextStatement:null,colour:'#ec9757'},{type:'cq_say',message0:'ให้ %1 พูด %2',args0:[{type:'field_dropdown',name:'ACTOR',options:[['บอท','bot'],['เพื่อน','friend']]},{type:'field_input',name:'TEXT',text:'สวัสดี!'}],previousStatement:null,nextStatement:null,colour:'#a080cb'});for(const[type,label]of [['start','เมื่อเริ่มเกม'],['key','เมื่อกด Space'],['touch','เมื่อแตะดาว'],['receive','เมื่อรับสัญญาณ']])defs.push({type:'cq_'+type,message0:label,nextStatement:null,colour:'#e5ad39',hat:'cap'});B.common.defineBlocksWithJsonArray(defs);}
export const BlocklyEditor=forwardRef<EditorHandle,Props>(function BlocklyEditor(p,ref){const host=useRef<HTMLDivElement>(null),ws=useRef<BlocklyType.WorkspaceSvg|null>(null),B=useRef<typeof BlocklyType|null>(null),latest=useRef(p);latest.current=p;const [category,setCategory]=useState('movement'),[ready,setReady]=useState(false);const [count,setCount]=useState(0);
const list=(cat:string)=>{const l=latest.current.level;let names=cat==='events'?['start',...(l.id>=10?['key','touch','receive']:[])]:l.blocks.filter(op=>cat==='movement'?['move','left','right'].includes(op):cat==='control'?op==='repeat':!['move','left','right','repeat'].includes(op));return{kind:'flyoutToolbox',contents:names.map(n=>({kind:'block',type:'cq_'+n}))}};
useEffect(()=>{let disposed=false;let observer:ResizeObserver;async function init(){try{const blockly=await import('blockly');const th=await import('blockly/msg/th');if(disposed||!host.current)return;B.current=blockly;blockly.setLocale(Object.fromEntries(Object.entries(th).filter(([,v])=>typeof v==='string')) as Record<string,string>);defineBlocks(blockly);const theme=blockly.Theme.defineTheme('quest',{name:'quest',base:blockly.Themes.Classic,fontStyle:{family:'Noto Sans Thai, sans-serif',weight:'500',size:12},componentStyles:{workspaceBackgroundColour:'#fbfcfa',toolboxBackgroundColour:'#f0f5ef',flyoutBackgroundColour:'#f0f5ef',flyoutOpacity:1,scrollbarColour:'#c6d8c9',insertionMarkerColour:'#84bf8c',insertionMarkerOpacity:.7}});
ws.current=blockly.inject(host.current,{toolbox:list('movement'),horizontalLayout:true,toolboxPosition:'start',theme,renderer:'zelos',sounds:false,trashcan:false,grid:{spacing:22,length:2,colour:'#d7e2d8',snap:false},move:{scrollbars:true,drag:true,wheel:true},zoom:{controls:false,wheel:false,startScale:.86,maxScale:1.4,minScale:.5,scaleSpeed:1.1}});blockly.serialization.workspaces.load(latest.current.saved||initialWorkspace(latest.current.level,latest.current.map),ws.current);ws.current.addChangeListener((e)=>{if(e.isUiEvent||!ws.current)return;const data=blockly.serialization.workspaces.save(ws.current);const n=ws.current.getAllBlocks(false).filter(b=>!['cq_start','cq_key','cq_touch','cq_receive'].includes(b.type)).length;setCount(n);latest.current.onChange(data,n);});observer=new ResizeObserver(()=>{if(ws.current)blockly.svgResize(ws.current)});observer.observe(host.current);setCount(ws.current.getAllBlocks(false).filter(b=>b.type!=='cq_start').length);setReady(true);latest.current.onReady();}catch(e){latest.current.onError('โหลดพื้นที่บล็อกไม่สำเร็จ กรุณาโหลดหน้าใหม่');console.error(e)}}init();return()=>{disposed=true;observer?.disconnect();ws.current?.dispose();ws.current=null}},[]);
useEffect(()=>{if(ready)ws.current?.updateToolbox(list(category))},[category,ready,p.level]);
useImperativeHandle(ref,()=>({program(){if(!ws.current)throw new Error('พื้นที่บล็อกกำลังโหลด');const result:Program={start:[],key:[],touch:[],receive:[]};const walk=(b:BlocklyType.Block|null,depth=0):Command[]=>{if(depth>8)throw new Error('บล็อกซ้อนกันเกิน 8 ชั้น');const out:Command[]=[];while(b){if(!b.isEnabled()){b=b.getNextBlock();continue}const op=b.type.replace('cq_','') as Op;if(!latest.current.level.blocks.includes(op))throw new Error('มีบล็อกที่ไม่อยู่ในบทเรียนนี้');const c:Command={op,id:b.id};if(op==='repeat'){c.count=Number(b.getFieldValue('TIMES'));c.body=walk(b.getInputTargetBlock('DO'),depth+1)}if(op==='say'){c.text=String(b.getFieldValue('TEXT')).slice(0,100);c.actor=b.getFieldValue('ACTOR')}out.push(c);b=b.getNextBlock();}return out};const seen=new Set<string>();for(const top of ws.current.getTopBlocks(true)){const event=top.type.replace('cq_','') as keyof Program;if(!(event in result))throw new Error('มีบล็อกที่ยังไม่เชื่อมต่อ ลองต่อใต้บล็อกเหตุการณ์หรือลบออก');if(seen.has(event))throw new Error('ใช้บล็อกเหตุการณ์ชนิดเดียวกันได้หนึ่งชุด');seen.add(event);result[event]=walk(top.getNextBlock());}return result;},save(){return ws.current&&B.current?B.current.serialization.workspaces.save(ws.current):null},load(data){if(ws.current&&B.current)B.current.serialization.workspaces.load(data,ws.current)},reset(){if(ws.current&&B.current)B.current.serialization.workspaces.load(initialWorkspace(latest.current.level,latest.current.map),ws.current)},highlight(id){ws.current?.highlightBlock(id||null)},insert(op){if(!ws.current||!B.current||!latest.current.level.blocks.includes(op))return;const b=ws.current.newBlock('cq_'+op);b.initSvg();b.render();const start=ws.current.getTopBlocks(true).find(b=>b.type==='cq_start');if(start){let end=start;while(end.getNextBlock())end=end.getNextBlock()!;if(end.nextConnection&&b.previousConnection)end.nextConnection.connect(b.previousConnection)}else b.moveBy(30,60)},}));
return <section className={'editor-card '+(p.locked?'editor-locked':'')}><div className="editor-title"><div><Puzzle size={19}/><h2>พื้นที่เขียนโปรแกรม</h2></div><span className="count-pill">{count} บล็อก</span></div><p className="editor-sub">ลากบล็อกมาต่อกัน แล้วดูไอเดียของเราเป็นจริง</p><Tabs value={category} onValueChange={setCategory}><TabsList className="block-tabs"><TabsTrigger value="movement">เคลื่อนที่</TabsTrigger>{p.level.blocks.some(b=>['pick','say','drop'].includes(b))&&<TabsTrigger value="action">การทำงาน</TabsTrigger>}{p.level.blocks.includes('repeat')&&<TabsTrigger value="control">ควบคุม</TabsTrigger>}<TabsTrigger value="events">เหตุการณ์</TabsTrigger></TabsList></Tabs><div className="blockly-host" ref={host} aria-label="พื้นที่ต่อบล็อก Blockly"/>{!ready&&<div className="blockly-loading">กำลังโหลดบล็อกคำสั่ง…</div>}<div className="editor-tools"><div><button title="ย้อนกลับ" aria-label="ย้อนกลับ" onClick={()=>ws.current?.undo(false)}><Undo2/></button><button title="ทำซ้ำการแก้ไข" aria-label="ทำซ้ำการแก้ไข" onClick={()=>ws.current?.undo(true)}><Redo2/></button><span/><button title="ขยายบล็อก" aria-label="ขยายบล็อก" onClick={()=>ws.current?.zoomCenter(1)}><ZoomIn/></button><button title="ย่อบล็อก" aria-label="ย่อบล็อก" onClick={()=>ws.current?.zoomCenter(-1)}><ZoomOut/></button></div><div><button title="ดูโค้ด" aria-label="ดูโค้ด" onClick={p.onCode}><Code2/></button><button title="บันทึกโปรแกรม" aria-label="บันทึกโปรแกรม" onClick={p.onSave}><Save/></button><button title="ล้างบล็อก" aria-label="ล้างบล็อก" onClick={p.onDelete}><Trash2/></button></div></div></section>
});
