'use client';
import { forwardRef, useEffect, useImperativeHandle, useRef, useState } from 'react';
import type { GameMap, GameState, Preferences } from '@/lib/game/types';
import { schoolModel } from '@/lib/school/client';
import {appUrl} from '@/lib/app-path';
import { key, same } from '@/lib/game/engine';
import { createSoftwareRenderer } from '@/lib/game/software-renderer';
import { Compass, RotateCcw, RotateCw, Plus, Minus, Maximize2, Home, Move, Loader2 } from 'lucide-react';
export type SceneHandle={animate:(state:GameState,animation:string,duration:number)=>Promise<void>;reset:(state:GameState)=>void;celebrate:()=>void;camera:(action:string)=>void};
type Props={map:GameMap;state:GameState;preferences:Preferences;npc?:boolean;schoolAsset?:{assetId:string;roomId:string};onReady:()=>void;onLoading:()=>void;onError:(m:string)=>void;onTouch:()=>void};
export const GameScene=forwardRef<SceneHandle,Props>(function GameScene(p,ref){const canvas=useRef<HTMLCanvasElement>(null),wrapper=useRef<HTMLDivElement>(null),api=useRef<any>(null),latest=useRef(p);latest.current=p;const [loaded,setLoaded]=useState(false),[error,setError]=useState('');const[angle,setAngle]=useState(0),[showMap,setShowMap]=useState(false);
useEffect(()=>{let disposed=false;let clean:()=>void=()=>{};async function init(){latest.current.onLoading();setError('');setLoaded(false);try{const B=await import('@/lib/game/babylon');await import('@babylonjs/loaders/glTF');if(disposed||!canvas.current)return;const hardware=B.Engine.isSupported();const engine:any=hardware?new B.Engine(canvas.current,true,{stencil:true,adaptToDeviceRatio:true,preserveDrawingBuffer:true}):new B.NullEngine({renderWidth:canvas.current.clientWidth,renderHeight:canvas.current.clientHeight,textureSize:512,deterministicLockstep:false,lockstepMaxSteps:4});engine.setHardwareScalingLevel(p.preferences.quality==='low'?1.65:Math.max(.8,1/(window.devicePixelRatio||1)));const scene=new B.Scene(engine);scene.useRightHandedSystem=true;const backgrounds={forest:'#e5f1e9',sunset:'#f5e9dd',sky:'#e5eff8'};const weather=p.preferences.weather||'sunny';const timeSetting=p.preferences.timeOfDay||'day';const hour=timeSetting==='auto'?new Date().getHours():timeSetting==='night'?22:timeSetting==='evening'?18:12;const night=hour<6||hour>=20,evening=hour>=16&&hour<20;const skyColor=night?'#17273f':weather==='storm'?'#728394':weather==='fog'?'#c1cac5':evening?'#f4c8aa':backgrounds[p.preferences.environment];scene.clearColor=B.Color4.FromHexString(skyColor+'ff');scene.ambientColor=new B.Color3(.45,.5,.4);const camera=new B.ArcRotateCamera('orbit',-Math.PI/2-0.57,.74,12.8,new B.Vector3(0,0,0),scene);if(hardware)camera.attachControl(canvas.current,true);const homeRadius=()=>Math.min(28,12.8*p.map.size/7*Math.max(1,(canvas.current?.clientHeight||482)*1.1/Math.max(1,canvas.current?.clientWidth||650)));camera.radius=homeRadius();camera.lowerBetaLimit=.36;camera.upperBetaLimit=1.14;camera.lowerRadiusLimit=7;camera.upperRadiusLimit=28;camera.wheelPrecision=35;camera.pinchPrecision=80;camera.panningSensibility=0;camera.inertia=.7;camera.minZ=.1;camera.fov=.72;const ambient=new B.HemisphericLight('sky',new B.Vector3(0,1,0),scene);ambient.intensity=1.05;ambient.groundColor=new B.Color3(.5,.61,.49);const sun=new B.DirectionalLight('sun',new B.Vector3(.5,-1,.45),scene);sun.position=new B.Vector3(-8,14,-8);sun.intensity=night?.55:weather==='storm'?1.2:evening?1.75:2.6;sun.direction=new B.Vector3(evening?.88:.5,-1,.45);if(['fog','rain','storm'].includes(weather)||night){scene.fogMode=B.Scene.FOGMODE_EXP2;scene.fogDensity=weather==='fog'?.065:weather==='storm'?.027:.016;scene.fogColor=B.Color3.FromHexString(skyColor)}const shadow=new B.ShadowGenerator(p.preferences.quality==='high'?2048:1024,sun);shadow.useBlurExponentialShadowMap=true;shadow.blurKernel=20;shadow.darkness=.25;scene.imageProcessingConfiguration.contrast=1.07;scene.imageProcessingConfiguration.exposure=1.15;scene.imageProcessingConfiguration.toneMappingEnabled=true;
const names=['island','grass','grass-light','path','water','bridge','tree','pine','rock','flower','star','parcel','key','gate','robot-'+p.preferences.character,'robot-violet'];const assets=new Map<string,any>();await Promise.all([...new Set(names)].map(async name=>{let modelUrl:string|undefined;try{if(p.schoolAsset&&name==='robot-'+p.preferences.character)modelUrl=await schoolModel(p.schoolAsset.assetId,p.schoolAsset.roomId);const a=await B.LoadAssetContainerAsync(modelUrl||appUrl('models/'+name+'.glb?v=5'),scene,{pluginExtension:'.glb'});assets.set(name,a)}finally{if(modelUrl)URL.revokeObjectURL(modelUrl)}}));if(disposed){scene.dispose();engine.dispose();return}
const objects:any[]=[];function place(name:string,pos:any,scale=1){const a=assets.get(name);const instance=a.instantiateModelsToScene((n:string)=>name+'-'+objects.length+'-'+n,false,{doNotInstantiate:false});const root=new B.TransformNode(name+'-instance',scene);for(const node of instance.rootNodes)node.parent=root;root.position=new B.Vector3(pos.x,pos.y||0,pos.z);root.scaling.setAll(scale);for(const m of root.getChildMeshes()){m.receiveShadows=true;if(p.preferences.quality!=='low'&&name!=='water'&&name!=='grass'&&name!=='grass-light'&&name!=='path')shadow.addShadowCaster(m);}
objects.push({root,groups:instance.animationGroups,name});return objects[objects.length-1]}
const center=(p.map.size-1)/2;const island=place('island',{x:0,z:0});island.root.scaling.set(p.map.size/7,1,p.map.size/7);const water=place('water',{x:0,y:-1.03,z:0});water.root.scaling.set(80,1,80);for(const m of water.root.getChildMeshes())m.receiveShadows=true;
const route=new Set(p.map.path.map(key));for(let z=0;z<p.map.size;z++)for(let x=0;x<p.map.size;x++){const isPath=route.has(`${x},${z}`);const stream=x===center;place(stream?(isPath?'bridge':'water'):isPath?'path':(x+z)%3===0?'grass-light':'grass',{x:x-center,y:stream&&!isPath?-.02:0,z:z-center});if(!isPath&&!stream){const obstacle=p.map.obstacles.some(o=>o.x===x&&o.z===z);if(obstacle){const type=(x*7+z)%5===0?'rock':(x+z)%2===0?'pine':'tree';const obj=place(type,{x:x-center+((z%2)*.15-.08),z:z-center},type==='rock'?.85:(.67+((x+z)%3)*.12));obj.root.rotation.y=x*z;}else if((x+z)%2===0){place('flower',{x:x-center-.18,z:z-center+.15},.9);place('flower',{x:x-center+.14,z:z-center-.12},.65)}}}
const star=place('star',{x:p.map.goal.x-center,y:.83,z:p.map.goal.z-center},1.05);const goalMat=new B.StandardMaterial('goal-ring-material',scene);goalMat.diffuseColor=B.Color3.FromHexString('#f7d176');goalMat.emissiveColor=B.Color3.FromHexString('#6c541d');const ring=B.MeshBuilder.CreateTorus('goal-ring',{diameter:.83,thickness:.06,tessellation:40},scene);ring.material=goalMat;ring.position.set(p.map.goal.x-center,.1,p.map.goal.z-center);
const bot=place('robot-'+p.preferences.character,{x:p.state.position.x-center,y:.11,z:p.state.position.z-center},1.0);bot.root.rotation.y=Math.PI-p.state.direction*Math.PI/2;if(['cobalt','coral'].includes(p.preferences.character)){const mat=new B.StandardMaterial('outfit-'+p.preferences.character,scene);mat.diffuseColor=B.Color3.FromHexString(p.preferences.character==='cobalt'?'#287fd4':'#e86f74');mat.specularColor=B.Color3.FromHexString('#9bb6bc');const pack=B.MeshBuilder.CreateBox('backpack',{width:.32,height:.42,depth:.17},scene);pack.material=mat;pack.parent=bot.root;pack.position.set(0,.56,.25);const badge=B.MeshBuilder.CreateTorus('outfit-badge',{diameter:.28,thickness:.065,tessellation:18},scene);badge.material=mat;badge.parent=bot.root;badge.position.set(0,1.04,0);badge.rotation.x=Math.PI/2;}
const friend=place('robot-violet',{x:2.2,y:.1,z:2.4},.69);friend.root.rotation.y=-2.5;friend.root.setEnabled(p.npc??p.map.levelId>=10);
const item=p.map.item?place(p.map.gate?'key':'parcel',{x:p.map.item.x-center,y:.13,z:p.map.item.z-center},1):null;
const gate=p.map.gate?place('gate',{x:p.map.gate.x-center,y:.1,z:p.map.gate.z-center},1):null;
const labels:any[]=[];function label(text:string,pos:any,color:string){const texture=new B.DynamicTexture('label-'+text,{width:128,height:128},scene,false);texture.hasAlpha=true;texture.drawText(text,null,92,'bold 94px sans-serif',color,'transparent',true);const m=new B.StandardMaterial('text-'+text,scene);m.diffuseTexture=texture;m.emissiveTexture=texture;m.useAlphaFromDiffuseTexture=true;m.backFaceCulling=false;const plane=B.MeshBuilder.CreatePlane('label-'+text,{size:.58},scene);plane.material=m;plane.position=pos;plane.rotation.x=-Math.PI/2;labels.push(plane)}
if(p.map.wrongGoal){label('X',new B.Vector3(p.map.goal.x-center,.13,p.map.goal.z-center),'#df7b61');label('O',new B.Vector3(p.map.wrongGoal.x-center,.13,p.map.wrongGoal.z-center),'#208563')}
// Small procedural details complement the bundled GLB models without extra downloads.
const cloudMat=new B.StandardMaterial('soft-cloud',scene);cloudMat.diffuseColor=B.Color3.FromHexString(night?'#8995ac':weather==='storm'?'#8f9ca8':'#f9faf1');cloudMat.alpha=.78;cloudMat.disableLighting=true;
const clouds:any[]=[];for(let i=0;i<(p.preferences.quality==='low'?2:5);i++){const c=B.MeshBuilder.CreateSphere('cloud-'+i,{diameter:1,segments:8},scene);c.material=cloudMat;c.position.set((i-2)*2.7,3.1+(i%2)*.3,-3.8+(i%3)*2.8);c.scaling.set(1.5,.27,.55);clouds.push(c)}
const orbMat=new B.StandardMaterial('sky-orb',scene);orbMat.emissiveColor=B.Color3.FromHexString(night?'#d5e5ff':'#ffe39a');orbMat.disableLighting=true;const orb=B.MeshBuilder.CreateSphere('sun-or-moon',{diameter:night?.48:.72,segments:16},scene);orb.material=orbMat;orb.position.set(evening?3:-3,3.5,-3.9);
const rain:any[]=[];if(weather==='rain'||weather==='storm')for(let i=0;i<(p.preferences.quality==='low'?24:p.preferences.quality==='high'?100:55);i++){const line=B.MeshBuilder.CreateLines('rain-'+i,{points:[new B.Vector3(0,0,0),new B.Vector3(.08,-.32,0)]},scene);line.color=B.Color3.FromHexString('#b8dceb');line.alpha=.55;line.position.set((i*17%101)/10-5,(i*29%47)/10,(i*37%101)/10-5);rain.push(line)}
const animated=objects.filter(o=>!['island','grass','grass-light','path','bridge','robot-'+p.preferences.character,'robot-violet','star','gate','water','key','parcel'].includes(o.name)).map((o,i)=>({o,i,y:o.root.position.y,rot:o.root.rotation.z}));
let playing='',previous:any,blend:any=null;function animateGroup(name:string){if(playing===name)return;playing=name;const next=bot.groups.find((g:any)=>g.name.endsWith(name));if(!next)return;for(const g of bot.groups)if(g!==previous&&g!==next)g.stop();next.start(true,1);next.setWeightForAllAnimatables(previous?0:1);blend=previous?{from:previous,to:next,start:performance.now()}:null;previous=next;}
function updateExtras(state:GameState){bot.root.setEnabled(state.visible);if(item){if(state.carrying){item.root.parent=bot.root;item.root.position.set(0,.54,.42);item.root.scaling.setAll(.75)}else if(state.delivered){item.root.parent=null;item.root.position.set(p.map.goal.x-center,.14,p.map.goal.z-center);item.root.setEnabled(true)}else{item.root.parent=null;item.root.position.set(p.map.item!.x-center,.13,p.map.item!.z-center);item.root.scaling.setAll(1);item.root.setEnabled(!state.picked)}}if(gate)gate.root.metadata={open:state.picked};}
let celebratingUntil=0;let motion:any=null;const pending=new Set<(v?:unknown)=>void>();let t=0;
const reset=(state:GameState)=>{if(motion){motion.resolve();motion=null;}bot.root.position.set(state.position.x-center,.11,state.position.z-center);bot.root.rotation.y=Math.PI-state.direction*Math.PI/2;updateExtras(state);animateGroup('Idle')};
const animate=(state:GameState,name:string,duration:number)=>new Promise<void>(resolve=>{animateGroup(name);const targetAngle=Math.PI-state.direction*Math.PI/2;let delta=targetAngle-bot.root.rotation.y;while(delta>Math.PI)delta-=Math.PI*2;while(delta< -Math.PI)delta+=Math.PI*2;motion={from:bot.root.position.clone(),to:new B.Vector3(state.position.x-center,.11,state.position.z-center),rot:bot.root.rotation.y,delta,start:performance.now(),duration,state,resolve};});
const cam=(action:string)=>{if(action==='left')camera.alpha-=Math.PI/2;if(action==='right')camera.alpha+=Math.PI/2;if(action==='in')camera.radius=Math.max(7,camera.radius-1.4);if(action==='out')camera.radius=Math.min(19,camera.radius+1.4);if(action==='reset'){camera.alpha=-Math.PI/2-.57;camera.beta=.74;camera.radius=homeRadius();}setAngle(Math.round((camera.alpha+Math.PI/2+.57)*180/Math.PI))};
api.current={animate,reset,celebrate(){celebratingUntil=performance.now()+2200;animateGroup('Celebrate')},camera:cam};reset(latest.current.state);friend.groups.find((g:any)=>g.name.endsWith('Idle'))?.start(true);
scene.onPointerObservable.add(info=>{if(info.type===B.PointerEventTypes.POINTERPICK&&info.pickInfo?.pickedMesh?.name.includes('star'))latest.current.onTouch()});
const software=hardware?null:createSoftwareRenderer(canvas.current,scene,camera,backgrounds[p.preferences.environment]);const resize=new ResizeObserver(()=>{if(hardware)engine.resize();if(canvas.current&&canvas.current.clientWidth<450)camera.radius=Math.max(camera.radius,homeRadius())});resize.observe(canvas.current);engine.runRenderLoop(()=>{if(blend){const f=Math.min(1,(performance.now()-blend.start)/180);blend.from.setWeightForAllAnimatables(1-f);blend.to.setWeightForAllAnimatables(f);if(f===1){blend.from.stop();blend=null}}t+=engine.getDeltaTime()/1000;for(const c of clouds)c.position.x=c.position.x>6?-6:c.position.x+engine.getDeltaTime()*.000075*(weather==='storm'?2:1);orb.position.y=3.3+Math.sin(t*.09)*.2;for(let i=0;i<rain.length;i++){const d=rain[i];d.position.y-=engine.getDeltaTime()*.005*(weather==='storm'?1.5:1);if(d.position.y<-.3)d.position.y=4.5}if(weather==='storm')sun.intensity=1.1+(Math.sin(t*11)> .995?2:0);if(p.preferences.quality!=='low')for(const {o,i,y,rot} of animated){o.root.rotation.z=rot+Math.sin(t*1.2+i*1.7)*(.02+(weather==='storm'?.045:0));if(o.name==='flower')o.root.position.y=y+Math.sin(t*1.9+i)*.018}if(item&&!item.root.parent&&!p.state.picked){item.root.rotation.y=t*1.1;item.root.position.y=.13+Math.sin(t*2)*.05}if(friend.root.isEnabled())friend.root.rotation.y=-2.5+Math.sin(t*.7)*.13;water.root.position.y=-1.03+Math.sin(t*1.1)*.014;star.root.position.y=.83+Math.sin(t*2)*.055;star.root.rotation.y=t*.55;ring.rotation.y=t*.2;if(gate)gate.root.scaling.y+=((gate.root.metadata?.open ? .15 : 1)-gate.root.scaling.y)*.12;if(performance.now()<celebratingUntil){ring.scaling.setAll(1+Math.sin(t*12)*.18);star.root.rotation.y+=.08}else ring.scaling.setAll(1);if(motion){const f=Math.min(1,(performance.now()-motion.start)/motion.duration),ease=f*f*(3-2*f);bot.root.position=B.Vector3.Lerp(motion.from,motion.to,ease);bot.root.rotation.y=motion.rot+motion.delta*ease;if(f>=1){const done=motion;motion=null;updateExtras(done.state);animateGroup('Idle');done.resolve()}}scene.render();software?.draw()});
const kb=(e:KeyboardEvent)=>{if((e.target as HTMLElement)?.closest('input,textarea,[contenteditable="true"],.blocklyWidgetDiv'))return;if(e.key.toLowerCase()==='z')cam('left');if(e.key.toLowerCase()==='r')cam('reset')};window.addEventListener('keydown',kb);setLoaded(true);latest.current.onReady();clean=()=>{if(motion)motion.resolve();window.removeEventListener('keydown',kb);resize.disconnect();software?.dispose();api.current=null;engine.stopRenderLoop();scene.dispose();assets.forEach(a=>a.dispose());engine.dispose()};}catch(e){if(disposed)return;setError('เปิดฉาก 3D ไม่สำเร็จ ลองเปิด WebGL หรือโหลดใหม่');latest.current.onError('ไม่สามารถโหลดฉาก 3D ได้');console.error(e)}}init();return()=>{disposed=true;clean()}},[p.map,p.preferences.character,p.preferences.environment,p.preferences.weather,p.preferences.timeOfDay,p.preferences.quality]);
useImperativeHandle(ref,()=>({animate:async(s,a,d)=>{await api.current?.animate(s,a,d)},reset:s=>api.current?.reset(s),celebrate:()=>api.current?.celebrate(),camera:a=>api.current?.camera(a)}));
return <section className="scene-card" ref={wrapper}><canvas ref={canvas} aria-label="ฉากเกม 3D หมุนด้วยการลาก ซูมด้วยล้อเมาส์หรือสองนิ้ว"/><div className="scene-top"><span className="scene-badge"><span/> โลก 3D ของเรา</span><button className="scene-icon" title="โหมดเกมเต็มจอ" aria-label="โหมดเกมเต็มจอ" onClick={async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await wrapper.current?.closest('.game-layout')?.requestFullscreen()}catch{latest.current.onError('อุปกรณ์นี้ไม่รองรับโหมดเต็มจอ')}}}><Maximize2 size={17}/></button></div><button className="minimap-toggle" aria-expanded={showMap} onClick={()=>setShowMap(v=>!v)}>แผนที่ {showMap?'−':'+'}</button>{showMap&&<div className="game-minimap" aria-label="แผนที่ย่อแสดงเส้นทางและตำแหน่งบอท"><div className="game-minimap-grid" style={{gridTemplateColumns:`repeat(${p.map.size},1fr)`}}>{Array.from({length:p.map.size*p.map.size},(_,i)=>{const x=i%p.map.size,z=Math.floor(i/p.map.size),path=p.map.path.some(n=>n.x===x&&n.z===z),bot=p.state.position.x===x&&p.state.position.z===z,goal=p.map.goal.x===x&&p.map.goal.z===z,item=p.map.item?.x===x&&p.map.item.z===z;return <span key={i} className={path?'path':''} title={bot?'บอท':goal?'ดาว':item?'ของ':''}>{bot?'🤖':goal?'⭐':item&&!p.state.picked?'◆':''}</span>})}</div></div>}<div className="compass"><Compass size={35} style={{transform:`rotate(${angle}deg)`}}/><span>N</span><small>บอทหัน {['N','E','S','W'][p.state.direction]}</small></div>{p.state.speech&&<div className={'speech-bubble '+(p.state.speaker==='friend'?'friend':'')}><b>{p.state.speaker==='friend'?'เพื่อน':'บอทน้อย'}</b><p>{p.state.speech}</p></div>}<div className="camera-controls"><button title="หมุนซ้าย (Z)" aria-label="หมุนกล้องซ้าย" onClick={()=>api.current?.camera('left')}><RotateCcw/></button><button title="หมุนขวา" aria-label="หมุนกล้องขวา" onClick={()=>api.current?.camera('right')}><RotateCw/></button><span/><button aria-label="ซูมเข้า" onClick={()=>api.current?.camera('in')}><Plus/></button><button aria-label="ซูมออก" onClick={()=>api.current?.camera('out')}><Minus/></button><span/><button title="มุมมองเริ่มต้น (R)" aria-label="คืนมุมมอง" onClick={()=>api.current?.camera('reset')}><Home/></button></div><div className="scene-help"><Move size={13}/> ลากเพื่อหมุน · เลื่อนเพื่อซูม</div>{(!loaded||error)&&<div className="scene-loading">{error?<><p>{error}</p><button className="primary-btn" onClick={()=>location.reload()}>โหลดอีกครั้ง</button></>:<><Loader2 className="spin" size={32}/><p>กำลังเตรียมโลก 3D…</p></>}</div>}</section>});
