/** Original procedural soundtrack: no remote audio, third-party songs or tracking. */
export type SoundCue='click'|'run'|'pause'|'stop'|'move'|'turn'|'pick'|'drop'|'hint'|'error'|'win'|'save';
export type AudioPreferences={sound:boolean;music:boolean;musicVolume:number;effectsVolume:number;environment:string};
const MIDI=(n:number)=>440*2**((n-69)/12);
const THEMES:Record<string,{bpm:number;chords:number[][];melody:number[]}>= {
 forest:{bpm:92,chords:[[48,52,55],[45,48,52],[41,45,48],[43,47,50]],melody:[72,76,79,76,74,72,69,72,76,79,81,79,76,74,72,0,69,72,76,72,67,69,72,0,74,76,79,74,71,74,72,0]},
 sunset:{bpm:76,chords:[[45,48,52],[41,45,48],[48,52,55],[43,47,50]],melody:[69,72,76,0,74,72,69,0,65,69,72,76,74,72,69,0,67,72,76,79,76,74,72,0,67,71,74,76,74,71,69,0]},
 sky:{bpm:104,chords:[[50,54,57],[47,50,54],[43,47,50],[45,49,52]],melody:[74,78,81,83,81,78,76,0,74,76,78,81,78,76,74,0,71,74,78,81,83,81,78,0,76,78,81,78,76,73,74,0]}
};
export class GameAudio {
 private ctx:AudioContext|null=null;private musicGain:GainNode|null=null;private fxGain:GainNode|null=null;private timer:ReturnType<typeof setInterval>|null=null;private next=0;private beat=0;private active=false;private hidden=false;private prefs:AudioPreferences={sound:true,music:true,musicVolume:30,effectsVolume:55,environment:'forest'};
 onState?:(state:string)=>void;
 configure(p:AudioPreferences){const change=p.environment!==this.prefs.environment;this.prefs=p;this.gains();if(change){this.beat=0;this.next=(this.ctx?.currentTime||0)+.12}this.schedule();this.report()}
 private report(){this.onState?.(!this.prefs.sound?'ปิดเสียงทั้งหมด':!this.active?'เพลงเริ่มเมื่อกดปุ่มในเกม':this.hidden?'พักเสียงเมื่อออกจากหน้าเกม':this.prefs.music?'กำลังเล่นเพลงประกอบ':'เปิดเฉพาะเสียงเอฟเฟกต์')}
 async unlock(){if(!this.ctx){const Constructor=window.AudioContext||(window as any).webkitAudioContext;if(!Constructor){this.onState?.('เบราว์เซอร์นี้ไม่รองรับเสียง');return}this.ctx=new Constructor();this.musicGain=this.ctx!.createGain();this.fxGain=this.ctx!.createGain();const compressor=this.ctx!.createDynamicsCompressor();compressor.threshold.value=-12;compressor.knee.value=15;compressor.ratio.value=4;this.musicGain.connect(compressor);this.fxGain.connect(compressor);compressor.connect(this.ctx!.destination);this.gains();this.next=this.ctx!.currentTime+.08;this.timer=setInterval(()=>this.schedule(),100)}try{await this.ctx!.resume();this.active=true;this.schedule();this.report()}catch{this.onState?.('แตะปุ่มเปิดเสียงเพื่อลองอีกครั้ง')}}
 private gains(){if(!this.ctx)return;const t=this.ctx.currentTime;this.musicGain?.gain.setTargetAtTime(this.prefs.sound&&this.prefs.music&&!this.hidden?this.prefs.musicVolume/100*.42:0,t,.08);this.fxGain?.gain.setTargetAtTime(this.prefs.sound&&!this.hidden?this.prefs.effectsVolume/100*.45:0,t,.03)}
 visibility(hidden:boolean){this.hidden=hidden;this.gains();if(!hidden&&this.ctx){this.next=this.ctx.currentTime+.1;this.ctx.resume().catch(()=>{})}this.report()}
 private note(midi:number,at:number,duration:number,volume:number,type:OscillatorType,bus:GainNode){if(!this.ctx||!midi)return;const osc=this.ctx.createOscillator(),gain=this.ctx.createGain();osc.type=type;osc.frequency.value=MIDI(midi);gain.gain.setValueAtTime(0,at);gain.gain.linearRampToValueAtTime(volume,at+.018);gain.gain.exponentialRampToValueAtTime(.0001,at+duration);osc.connect(gain);gain.connect(bus);osc.start(at);osc.stop(at+duration+.02);osc.onended=()=>{osc.disconnect();gain.disconnect()}}
 private schedule(){if(!this.active||!this.ctx||!this.musicGain||!this.prefs.sound||!this.prefs.music||this.hidden)return;const track=THEMES[this.prefs.environment]||THEMES.forest,unit=60/track.bpm/2;if(this.next<this.ctx.currentTime)this.next=this.ctx.currentTime+.05;while(this.next<this.ctx.currentTime+.25){const b=this.beat,chord=track.chords[Math.floor(b/8)%track.chords.length],melody=track.melody[b%track.melody.length];this.note(melody,this.next,unit*1.6,.15,'sine',this.musicGain);this.note(chord[b%3]+12,this.next,unit*1.8,.065,'triangle',this.musicGain);if(b%8===0){this.note(chord[0]-12,this.next,unit*6,.14,'sine',this.musicGain);for(const n of chord)this.note(n,this.next,unit*7,.035,'sine',this.musicGain)}this.next+=unit;this.beat++}}
 cue(cue:SoundCue){if(!this.active||!this.ctx||!this.fxGain||!this.prefs.sound||this.hidden)return;const seq:Record<SoundCue,number[]>={click:[79],run:[60,64,67],pause:[72,67],stop:[64,60],move:[60],turn:[67],pick:[76,83],drop:[79,72],hint:[72,76,79],error:[55,53],win:[72,76,79,84,83,84],save:[72,79]};const notes=seq[cue],t=this.ctx.currentTime,d=cue==='win'?.19:cue==='error'?.15:.075;notes.forEach((n,i)=>this.note(n,t+i*d,cue==='win'?.45:.16,cue==='move'?.045:cue==='click'?.1:.16,cue==='error'?'triangle':'sine',this.fxGain!))}
 dispose(){if(this.timer)clearInterval(this.timer);this.timer=null;this.ctx?.close().catch(()=>{});this.ctx=null;this.active=false}
}
