/** CPU projection of the same Babylon/GLB meshes when WebGL is unavailable. */
export function createSoftwareRenderer(canvas:HTMLCanvasElement,scene:any,camera:any,background:string){
 const ctx=canvas.getContext('2d',{alpha:false});if(!ctx)throw new Error('อุปกรณ์นี้ไม่รองรับการวาดภาพ');let width=0,height=0,last=0,drag:any=null;
 const resize=()=>{width=Math.max(1,canvas.clientWidth);height=Math.max(1,canvas.clientHeight);canvas.width=width;canvas.height=height;scene.getEngine().setSize(width,height);camera.getProjectionMatrix(true)};
 const wheel=(e:WheelEvent)=>{e.preventDefault();camera.radius=Math.max(7,Math.min(19,camera.radius+Math.sign(e.deltaY)*.6))};
 const pointers=new Map<number,{x:number;y:number}>();let pinch=0;
 const distance=()=>{const a=[...pointers.values()];return a.length===2?Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y):0};
 const pointer=(e:PointerEvent)=>{pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});drag={x:e.clientX,y:e.clientY};pinch=distance();canvas.setPointerCapture(e.pointerId)};
 const move=(e:PointerEvent)=>{if(!pointers.has(e.pointerId))return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===2){const d=distance();if(pinch>0&&d>0)camera.radius=Math.max(7,Math.min(19,camera.radius*pinch/d));pinch=d;drag=null;return}if(!drag){drag={x:e.clientX,y:e.clientY};return}camera.alpha-=(e.clientX-drag.x)*.008;camera.beta=Math.max(.36,Math.min(1.14,camera.beta+(e.clientY-drag.y)*.006));drag={x:e.clientX,y:e.clientY}};
 const up=(e:PointerEvent)=>{pointers.delete(e.pointerId);drag=null;pinch=0};canvas.addEventListener('wheel',wheel,{passive:false});canvas.addEventListener('pointerdown',pointer);canvas.addEventListener('pointermove',move);canvas.addEventListener('pointerup',up);canvas.addEventListener('pointercancel',up);
 const cache=new Map<any,any>();let disposed=false;
 const draw=()=>{if(disposed)return;const now=performance.now();if(now-last<85)return;last=now;if(width!==canvas.clientWidth||height!==canvas.clientHeight)resize();ctx.fillStyle=background;ctx.fillRect(0,0,width,height);const tris:any[]=[];scene.updateTransformMatrix(true);const transform=scene.getTransformMatrix();
 for(const mesh of scene.meshes){if(mesh.name.startsWith('water-1-')||!mesh.isEnabled()||!mesh.isVisible||mesh.visibility<=0||mesh.name.startsWith('label-'))continue;if(mesh.skeleton){mesh.skeleton.prepare();mesh.applySkeleton(mesh.skeleton)}let geo=cache.get(mesh);if(!geo){const pos=mesh.getVerticesData('position'),ind=mesh.getIndices(),norm=mesh.getVerticesData('normal');if(!pos||!ind)continue;const mat=mesh.material;const c=mat?.albedoColor||mat?.diffuseColor||{r:.7,g:.8,b:.6};geo={pos,ind,norm,color:mesh.name.startsWith('water-1-')?[.86,.93,.89]:[c.r,c.g,c.b].map(v=>Math.pow(v,1/2.2))};cache.set(mesh,geo)}
 if(mesh.skeleton){geo.pos=mesh.getVerticesData('position');geo.norm=mesh.getVerticesData('normal')}const world=mesh.computeWorldMatrix(true),m=world.multiply(transform).m,w=world.m,projected=new Float32Array(geo.pos.length),shades=new Float32Array(geo.pos.length/3);
 for(let i=0;i<geo.pos.length;i+=3){const x=geo.pos[i],y=geo.pos[i+1],z=geo.pos[i+2],cw=x*m[3]+y*m[7]+z*m[11]+m[15];projected[i]=((x*m[0]+y*m[4]+z*m[8]+m[12])/cw*.5+.5)*width;projected[i+1]=(1-((x*m[1]+y*m[5]+z*m[9]+m[13])/cw*.5+.5))*height;projected[i+2]=(x*m[2]+y*m[6]+z*m[10]+m[14])/cw;
 const n=geo.norm;if(n){const nx=n[i]*w[0]+n[i+1]*w[4]+n[i+2]*w[8],ny=n[i]*w[1]+n[i+1]*w[5]+n[i+2]*w[9],nz=n[i]*w[2]+n[i+1]*w[6]+n[i+2]*w[10],len=Math.hypot(nx,ny,nz)||1;shades[i/3]=.82+.25*Math.max(0,(-.45*nx+.8*ny-.4*nz)/len)}else shades[i/3]=.95;}
 for(let i=0;i<geo.ind.length;i+=3){const a=geo.ind[i]*3,b=geo.ind[i+1]*3,c=geo.ind[i+2]*3,ax=projected[a],ay=projected[a+1],bx=projected[b],by=projected[b+1],cx=projected[c],cy=projected[c+1],z=(projected[a+2]+projected[b+2]+projected[c+2])/3;if(z>1||z<0||Math.max(ax,bx,cx)<0||Math.min(ax,bx,cx)>width||Math.max(ay,by,cy)<0||Math.min(ay,by,cy)>height)continue;const area=(bx-ax)*(cy-ay)-(by-ay)*(cx-ax);if(Math.abs(area)<.16)continue;const shade=(shades[a/3]+shades[b/3]+shades[c/3])/3;tris.push([z,ax,ay,bx,by,cx,cy,geo.color.map((v:number)=>Math.min(255,Math.round(v*255*shade))),mesh.name,projected[a+2],projected[b+2],projected[c+2]]);}
 }
 const frame=ctx.createImageData(width,height),pixels=frame.data,depthBuffer=new Float32Array(width*height);depthBuffer.fill(Infinity);const bg=background.replace('#','');const br=parseInt(bg.slice(0,2),16),bgc=parseInt(bg.slice(2,4),16),bb=parseInt(bg.slice(4,6),16);for(let i=0;i<pixels.length;i+=4){pixels[i]=br;pixels[i+1]=bgc;pixels[i+2]=bb;pixels[i+3]=255;}
 for(const t of tris){const ax=t[1],ay=t[2],bx=t[3],by=t[4],cx=t[5],cy=t[6],minX=Math.max(0,Math.floor(Math.min(ax,bx,cx))),maxX=Math.min(width-1,Math.ceil(Math.max(ax,bx,cx))),minY=Math.max(0,Math.floor(Math.min(ay,by,cy))),maxY=Math.min(height-1,Math.ceil(Math.max(ay,by,cy))),den=(by-cy)*(ax-cx)+(cx-bx)*(ay-cy);if(Math.abs(den)<.01)continue;const inv=1/den;for(let y=minY;y<=maxY;y++)for(let x=minX;x<=maxX;x++){const u=((by-cy)*(x+.5-cx)+(cx-bx)*(y+.5-cy))*inv,v=((cy-ay)*(x+.5-cx)+(ax-cx)*(y+.5-cy))*inv,w=1-u-v;if(u<-.001||v<-.001||w<-.001)continue;const depth=u*t[9]+v*t[10]+w*t[11],pixel=y*width+x;if(depth>=depthBuffer[pixel])continue;depthBuffer[pixel]=depth;const i=pixel*4;pixels[i]=t[7][0];pixels[i+1]=t[7][1];pixels[i+2]=t[7][2];}}
 ctx.putImageData(frame,0,0);
 // O/X markers are projected game labels on the actual map cells.
 for(const label of scene.meshes.filter((m:any)=>m.name.startsWith('label-'))){const p=label.position,m=transform.m,cw=p.x*m[3]+p.y*m[7]+p.z*m[11]+m[15],x=((p.x*m[0]+p.y*m[4]+p.z*m[8]+m[12])/cw*.5+.5)*width,y=(1-((p.x*m[1]+p.y*m[5]+p.z*m[9]+m[13])/cw*.5+.5))*height;ctx.font='bold 22px sans-serif';ctx.textAlign='center';ctx.fillStyle=label.name==='label-X'?'#bd7656':'#3e8862';ctx.fillText(label.name.slice(6),x,y);}
 };
 resize();return{draw,dispose(){disposed=true;canvas.removeEventListener('wheel',wheel);canvas.removeEventListener('pointerdown',pointer);canvas.removeEventListener('pointermove',move);canvas.removeEventListener('pointerup',up);canvas.removeEventListener('pointercancel',up);cache.clear()}};
}
