import { NullEngine, Scene, Mesh, MeshBuilder, StandardMaterial, Color3, Vector3, TransformNode, Animation, AnimationGroup, VertexData, Skeleton, Bone, Matrix, Quaternion, VertexBuffer } from '@babylonjs/core';
import { GLTF2Export } from '@babylonjs/serializers/glTF/index.js';
import { mkdir, writeFile } from 'node:fs/promises';
const engine = new NullEngine();
await mkdir('public/models',{recursive:true});
function mat(scene,name,color){const m=new StandardMaterial(name,scene);m.diffuseColor=Color3.FromHexString(color);m.specularColor=new Color3(.12,.12,.12);return m;}
function roundBox(name,w,h,d,r,scene,m,pos=[0,0,0],parent=null){r=Math.min(r,w/2,h/2,d/2)*.999;const p=[],n=[],idx=[];const dims=[w/2,h/2,d/2],steps=8;for(let face=0;face<6;face++){const axis=Math.floor(face/2),sign=face%2===0?1:-1,a=(axis+1)%3,b=(axis+2)%3,base=p.length/3;for(let i=0;i<=steps;i++)for(let j=0;j<=steps;j++){const v=[0,0,0];v[axis]=dims[axis]*sign;v[a]=(2*i/steps-1)*dims[a];v[b]=(2*j/steps-1)*dims[b];const c=v.map((x,k)=>Math.max(-dims[k]+r,Math.min(dims[k]-r,x)));const norm=v.map((x,k)=>x-c[k]);const len=Math.hypot(...norm)||1;for(let k=0;k<3;k++){p.push(c[k]+norm[k]/len*r);n.push(norm[k]/len);}}for(let i=0;i<steps;i++)for(let j=0;j<steps;j++){const k=base+i*(steps+1)+j;if(sign>0)idx.push(k,k+1,k+steps+1,k+1,k+steps+2,k+steps+1);else idx.push(k,k+steps+1,k+1,k+1,k+steps+1,k+steps+2);}}
const mesh=new Mesh(name,scene),vd=new VertexData();vd.positions=p;vd.normals=n;vd.indices=idx;vd.applyToMesh(mesh);mesh.material=m;mesh.position=new Vector3(...pos);mesh.parent=parent;return mesh;}
function sphere(name,scale,scene,m,pos=[0,0,0],parent=null){const x=MeshBuilder.CreateSphere(name,{diameter:1,segments:12},scene);x.scaling=new Vector3(...scale);x.position=new Vector3(...pos);x.material=m;x.parent=parent;return x;}
function cylinder(name,h,top,bottom,scene,m,pos=[0,0,0],parent=null){const x=MeshBuilder.CreateCylinder(name,{height:h,diameterTop:top,diameterBottom:bottom,tessellation:16},scene);x.position=new Vector3(...pos);x.material=m;x.parent=parent;return x;}
async function asset(name,build){const s=new Scene(engine);s.useRightHandedSystem=true;await build(s);const glb=await GLTF2Export.GLBAsync(s,name,{exportWithoutWaitingForScene:true,removeNoopRootNodes:false});for(const [file,blob]of Object.entries(glb.glTFFiles))await writeFile('public/models/'+file,Buffer.from(await blob.arrayBuffer()));s.dispose();}
for(const [name,col]of [['grass','#a5cb77'],['grass-light','#b4d988'],['path','#e8d6a6'],['water','#81cee0']])await asset(name,s=>{roundBox(name,1,.18,1,.09,s,mat(s,'surface',col),[0,-.09,0]);});
await asset('island',s=>{roundBox('earth',7.25,.76,7.25,.35,s,mat(s,'earth','#9a9572'),[0,-.48,0]);roundBox('rim',7.3,.28,7.3,.2,s,mat(s,'edge','#759f63'),[0,-.20,0]);roundBox('under',6.65,.35,6.65,.17,s,mat(s,'bottom','#838667'),[0,-.93,0]);});
await asset('bridge',s=>{const wood=mat(s,'wood','#bba277');for(let i=0;i<5;i++)roundBox('plank'+i,.95,.14,.175,.025,s,wood,[0,.03,i*.18-.36]);const rail=mat(s,'rail','#d6bc89');for(const x of[-.42,.42])roundBox('rail',.08,.1,1.0,.035,s,rail,[x,.22,0]);});
await asset('tree',s=>{const bark=mat(s,'bark','#ad8861'),leaf=mat(s,'leaf','#5eaa71'),top=mat(s,'leaf-top','#80bb77');cylinder('trunk',.75,.18,.25,s,bark,[0,.25,0]);sphere('crown',[.98,1.10,.96],s,leaf,[0,.94,0]);sphere('crown-top',[.75,.8,.75],s,top,[-.05,1.33,-.04]);});
await asset('pine',s=>{const bark=mat(s,'bark','#ae8e68');cylinder('trunk',.7,.15,.2,s,bark,[0,.2,0]);cylinder('leaf-bottom',1.05,.09,1.02,s,mat(s,'pine','#43976e'),[0,.82,0]);cylinder('leaf-top',.92,0,.75,s,mat(s,'pine-top','#68b27d'),[0,1.25,0]);});
await asset('rock',s=>{sphere('stone',[.62,.38,.52],s,mat(s,'stone','#94ada1'),[0,.08,0]);sphere('stone-small',[.35,.26,.31],s,mat(s,'stone-light','#b9cabe'),[.2,.04,.2]);});
await asset('flower',s=>{cylinder('stem',.22,.026,.03,s,mat(s,'stem','#5b9d63'),[0,.11,0]);const white=mat(s,'petals','#fffde9');for(let i=0;i<5;i++){const a=i*Math.PI*2/5;sphere('petal',[.13,.055,.13],s,white,[Math.cos(a)*.07,.25,Math.sin(a)*.07]);}sphere('center',[.1,.07,.1],s,mat(s,'yellow','#edbf4c'),[0,.28,0]);});
await asset('star',s=>{const gold=mat(s,'gold','#ffd363');gold.emissiveColor=new Color3(.15,.085,0);const pts=[];for(let i=0;i<10;i++){const a=Math.PI/2+i*Math.PI/5,r=i%2===0?.4:.185;pts.push(new Vector3(Math.cos(a)*r,Math.sin(a)*r,0));}const positions=[],indices=[];for(let z of[-.065,.065]){positions.push(0,0,z);for(const p of pts)positions.push(p.x,p.y,z);}for(let i=0;i<10;i++){const j=(i+1)%10;indices.push(0,j+1,i+1,11,i+12,j+12,i+1,j+1,i+12,j+1,j+12,i+12);}const normals=[];VertexData.ComputeNormals(positions,indices,normals);const mesh=new Mesh('star',s),vd=new VertexData();vd.positions=positions;vd.indices=indices;vd.normals=normals;vd.applyToMesh(mesh);mesh.material=gold;});
await asset('parcel',s=>{const m=mat(s,'package','#d9a768');roundBox('box',.43,.43,.43,.04,s,m,[0,.215,0]);roundBox('ribbon',.09,.45,.45,.01,s,mat(s,'ribbon','#ffe0a0'),[0,.225,0]);});
await asset('key',s=>{const m=mat(s,'gold','#ffd262');const ring=MeshBuilder.CreateTorus('key-ring',{diameter:.3,thickness:.08,tessellation:20},s);ring.material=m;ring.position.y=.3;roundBox('shaft',.08,.1,.38,.02,s,m,[0,.3,.27]);roundBox('tooth',.18,.1,.07,.02,s,m,[.05,.3,.41]);});
await asset('gate',s=>{const m=mat(s,'gate','#af8361');for(const x of[-.42,.42])roundBox('post',.17,1,.17,.055,s,m,[x,.5,0]);roundBox('beam',1.03,.16,.17,.05,s,m,[0,1,0]);const gold=mat(s,'bars','#e5bd64');for(const x of[-.25,0,.25])roundBox('bar',.075,.75,.075,.02,s,gold,[x,.45,0]);});
for(const [name,color] of [['mint','#86cdae'],['sunny','#f2ca67'],['violet','#ad9be2']])await asset('robot-'+name,s=>{
const root=new TransformNode('rig',s),white=mat(s,'ceramic','#f3f6e9'),mint=mat(s,'accent',color),dark=mat(s,'face','#27463e'),eye=mat(s,'eyes','#cbf9d7');eye.emissiveColor=new Color3(.3,.55,.35);
roundBox('body',.46,.44,.35,.12,s,mint,[0,.53,0],root);roundBox('badge',.17,.13,.028,.035,s,white,[0,.56,.18],root);
const head=new TransformNode('head-joint',s);head.parent=root;head.position.y=.97;roundBox('head',.71,.55,.52,.17,s,white,[0,0,0],head);roundBox('screen',.56,.3,.09,.1,s,dark,[0,0,.25],head);
for(const x of[-.13,.13])roundBox('eye',.07,.1,.028,.028,s,eye,[x,.015,.308],head);
roundBox('smile',.11,.026,.02,.008,s,eye,[0,-.08,.31],head);cylinder('antenna',.15,.045,.045,s,mint,[0,.33,0],head);sphere('antenna-tip',[.115,.115,.115],s,mat(s,'antenna-light','#ffcf60'),[0,.43,0],head);
for(const side of[-1,1]){const arm=new TransformNode(side<0?'arm-left':'arm-right',s);arm.parent=root;arm.position=new Vector3(side*.31,.68,0);roundBox('arm',.14,.31,.17,.066,s,white,[0,-.12,0],arm);sphere('hand',[.17,.16,.17],s,mint,[0,-.27,0],arm);const leg=new TransformNode(side<0?'leg-left':'leg-right',s);leg.parent=root;leg.position=new Vector3(side*.14,.34,0);roundBox('leg',.18,.23,.19,.07,s,mint,[0,-.11,0],leg);roundBox('foot',.22,.13,.30,.057,s,white,[0,-.27,.04],leg);}
const skeleton=new Skeleton('robot-skeleton','robot-skeleton',s),joints=[root,head,...['arm-left','arm-right','leg-left','leg-right'].map(n=>s.getTransformNodeByName(n))],bones=new Map();
for(const node of joints){const bone=new Bone(node.name,skeleton,bones.get(node.parent)||null,Matrix.Compose(node.scaling,Quaternion.FromEulerVector(node.rotation),node.position));bone.linkTransformNode(node);bones.set(node,bone)}
for(const mesh of [...s.meshes]){const parent=mesh.parent,bone=bones.get(parent)||bones.get(root),world=mesh.computeWorldMatrix(true).clone();mesh.bakeTransformIntoVertices(world);mesh.parent=null;mesh.position.setAll(0);mesh.rotation.setAll(0);mesh.rotationQuaternion=Quaternion.Identity();mesh.scaling.setAll(1);const count=mesh.getTotalVertices(),indices=new Float32Array(count*4),weights=new Float32Array(count*4);for(let i=0;i<count;i++){indices[i*4]=skeleton.bones.indexOf(bone);weights[i*4]=1}mesh.setVerticesData(VertexBuffer.MatricesIndicesKind,indices);mesh.setVerticesData(VertexBuffer.MatricesWeightsKind,weights);mesh.skeleton=skeleton;mesh.numBoneInfluencers=1;mesh.computeWorldMatrix(true)}
skeleton.prepare();
const armL=s.getTransformNodeByName('arm-left'),armR=s.getTransformNodeByName('arm-right'),legL=s.getTransformNodeByName('leg-left'),legR=s.getTransformNodeByName('leg-right');
for(const name of['Idle','Walk','Run','TurnLeft','TurnRight','PickUp','Carry','Drop','Talk','Happy','Wrong','Celebrate']){const g=new AnimationGroup(name,s);const dur=name==='Run'?18:36;for(const [j,node]of [armL,armR,legL,legR,head].entries()){const a=new Animation(name+'-'+j,'rotation.x',30,Animation.ANIMATIONTYPE_FLOAT,Animation.ANIMATIONLOOPMODE_CYCLE);let v=name==='Walk'||name==='Run'?.5:name==='Celebrate'||name==='Happy'?.8:name==='PickUp'||name==='Drop'?.65:name==='Talk'?.12:.03;const sign=j%2===0?1:-1;a.setKeys([{frame:0,value:0},{frame:dur/4,value:v*sign},{frame:dur*3/4,value:-v*sign},{frame:dur,value:0}]);g.addTargetedAnimation(a,node);}}
});
engine.dispose();console.log('Created GLB assets with character animation groups.');
