const fs=require('node:fs');fs.mkdirSync(require('node:path').join(__dirname,'../.qa/core'),{recursive:true});fs.writeFileSync(require('node:path').join(__dirname,'../.qa/core/package.json'),'{"type":"commonjs"}');
const assert=require('node:assert/strict');const {LEVELS,getLevel}=require('../.qa/core/curriculum.js');const {generateMap,initialState,transition,completion,expand,scoreResult,solve}=require('../.qa/core/engine.js');
let checks=0,maps=0;function check(name,fn){fn();checks++;console.log('PASS '+name)}
check('All 21 levels exist and keep tutorial separate',()=>{assert.equal(LEVELS.length,21);assert.equal(getLevel(20).kind,'story');assert.deepEqual(scoreResult(getLevel(0),generateMap(getLevel(0),'TEST'),3,1,30),{score:0,stars:0})});
check('1890 seeded maps are reproducible and solver solutions execute',()=>{for(const level of LEVELS)for(const d of ['easy','normal','hard'])for(let i=0;i<30;i++){const seed='P4-QA-'+i,m=generateMap(level,seed,d);assert.deepEqual(m,generateMap(level,seed,d));let state=initialState(m,true);for(const c of m.optimal)state=transition(state,c,m);assert.deepEqual(state.position,m.goal);if(level.kind==='delivery')assert.equal(state.delivered,true);maps++;}});
check('Different seeds vary map layout and start direction',()=>{const seen=new Set(Array.from({length:12},(_,i)=>JSON.stringify(generateMap(getLevel(1),'RANDOM-'+i))));assert.ok(seen.size>6)});
check('Wall collisions fail without mutating original state',()=>{const m=generateMap(getLevel(1),'QA-2026');const s=initialState(m);const left=transition(s,{op:'left'},m);assert.throws(()=>transition(left,{op:'move'},m));assert.equal(s.direction,0)});
check('Missing key cannot pass locked gate',()=>{const m=generateMap(getLevel(2),'QA-2026');let s=initialState(m);assert.throws(()=>{for(const c of m.optimal.filter(c=>c.op!=='pick'))s=transition(s,c,m)},/ประตู/)});
check('Delivery requires pickup and drop at goal',()=>{const l=getLevel(6),m=generateMap(l,'QA-2026');let s=initialState(m);for(const c of m.optimal.filter(c=>c.op!=='drop'))s=transition(s,c,m);assert.equal(completion(l,m,s,{prediction:true,storyboard:true,customize:true}).won,false);s=transition(s,{op:'drop'},m);assert.equal(completion(l,m,s,{prediction:true,storyboard:true,customize:true}).won,true)});
check('Energy exhaustion stops execution',()=>{const m=generateMap(getLevel(1),'QA-2026');const s=initialState(m);s.energy=0;assert.throws(()=>transition(s,{op:'move'},m),/พลังงาน/)});
check('Loops obey nesting and execution limits',()=>{assert.equal(expand([{op:'repeat',count:4,body:[{op:'move'}]}]).length,5);assert.throws(()=>expand([{op:'repeat',count:0,body:[]} ]));let c={op:'move'};for(let i=0;i<10;i++)c={op:'repeat',count:2,body:[c]};assert.throws(()=>expand([c]));assert.throws(()=>expand([{op:'repeat',count:20,body:[{op:'repeat',count:20,body:[{op:'move'},{op:'move'}]}]}]))});
check('All mission objectives reject incomplete work and accept matching work',()=>{for(const l of LEVELS){const m=generateMap(l,'TEST-2026'),context={prediction:true,storyboard:true,customize:true};let s=initialState(m);assert.equal(completion(l,m,s,{prediction:false,storyboard:false,customize:false}).won,false);for(const c of m.optimal)s=transition(s,c,m);s.features=['event','key','broadcast','receive','repeat','say','friend','hide','show'];s.steps=Math.max(4,s.steps);s.log=['bot: เริ่มต้น','bot: ปัญหา','friend: แก้แล้ว'];s.ended=true;assert.equal(completion(l,m,s,context).won,true,l.title)}});
check('Scores stay within 0–100 and never reward slower or extra attempts',()=>{const l=getLevel(1),m=generateMap(l,'TEST');for(let i=1;i<100;i++){const a=scoreResult(l,m,i,i,i*60);assert.ok(a.score>=0&&a.score<=100);assert.ok(a.stars>=1&&a.stars<=3)}const a=scoreResult(l,m,8,1,60),b=scoreResult(l,m,8,5,600);assert.ok(a.score>=b.score)});
check('Seed validation rejects invalid payloads',()=>{for(const seed of ['','bad seed','<script>','a'.repeat(65)])assert.throws(()=>generateMap(getLevel(1),seed))});
console.log(JSON.stringify({checks,maps,status:'PASS'}));
