// Integration tests use the actual Firestore/Auth emulators. Never run on production.
const assert=require('node:assert/strict');
const fs=require('node:fs');
if(process.env.FIRESTORE_EMULATOR_HOST!=='127.0.0.1:8080'||process.env.GCLOUD_PROJECT!=='demo-code-quest')throw Error('Tests require the isolated demo-code-quest emulator');
const {execute,db}=require('../firebase/functions/lib/firebase/functions/src/service.js');
const {getAuth}=require('firebase-admin/auth');
const {initialState,generateMap}=require('../firebase/functions/lib/lib/game/engine.js');
const {getLevel}=require('../firebase/functions/lib/lib/game/curriculum.js');
const {initializeTestEnvironment,assertFails,assertSucceeds}=require('@firebase/rules-unit-testing');
const {doc,getDoc,setDoc}=require('firebase/firestore');
const school='test-school',other='other-school',pass='Test-only-passphrase-2026';let checks=0;
async function test(name,fn){await fn();checks++;console.log('PASS',name)}
async function rejects(fn,pattern){await assert.rejects(fn,pattern)}
async function user(uid,role,schoolId=school){await getAuth().createUser({uid,email:uid+'@example.test',password:pass});await db.doc('users/'+uid).set({schoolId,role,name:uid,email:uid+'@example.test',active:true})}
(async()=>{
 await fetch('http://127.0.0.1:8080/emulator/v1/projects/demo-code-quest/databases/(default)/documents',{method:'DELETE'});
 await fetch('http://127.0.0.1:9099/emulator/v1/projects/demo-code-quest/accounts',{method:'DELETE'});
 await db.doc('schools/'+school).set({name:'โรงเรียนทดสอบ'});await db.doc('schools/'+other).set({name:'อีกโรงเรียน'});
 await user('admin-a','admin');await user('teacher-a','teacher');await user('teacher-b','teacher');await user('admin-b','admin',other);
 const first=await execute('admin-a','saveClass',{className:'ป.4/1',grade:'ป.4',roomNumber:'1',academicYear:2569,semester:1,teacherIds:['teacher-a'],status:'active'});
 const second=await execute('admin-a','saveClass',{className:'ป.4/2',grade:'ป.4',roomNumber:'2',academicYear:2569,semester:1,teacherIds:['teacher-b'],status:'active'});
 const next=await execute('admin-a','saveClass',{className:'ป.5/1',grade:'ป.5',roomNumber:'1',academicYear:2570,semester:1,teacherIds:['teacher-a'],status:'active'});
 const base=(n)=>({studentCode:String(n).padStart(5,'0'),prefix:'ด.ช.',firstName:'ชื่อซ้ำ',lastName:'ทดสอบ',nickname:'นักคิด '+n,classId:first.id,studentNumber:n,status:'active'});
 let roster;
 await test('Import preview writes no students; 40 rows import exactly once with leading zeros',async()=>{const rows=Array.from({length:40},(_,i)=>({rowId:String(i+2),student:base(i+1)}));for(let i=0;i<40;i+=20){const batch=rows.slice(i,i+20);const p=await execute('teacher-a','import',{jobId:'job-40',rows:batch,preview:true,mode:'update'});assert(p.every(x=>x.ok&&x.action==='new'))}assert.equal((await execute('teacher-a','students',{})).total,0);for(let i=0;i<40;i+=20){const p={jobId:'job-40',rows:rows.slice(i,i+20),preview:false,mode:'update'};const a=await execute('teacher-a','import',p),b=await execute('teacher-a','import',p);assert.deepEqual(a,b);assert(a.every(x=>x.ok))}roster=(await execute('teacher-a','students',{pageSize:100})).rows;assert.equal(roster.length,40);assert.equal(new Set(roster.map(s=>s.id)).size,40);assert.equal(roster[0].studentCode,'00001')});
 await test('Duplicate code / duplicate number / missing fields and unauthorized class rejected',async()=>{await rejects(()=>execute('teacher-a','saveStudent',base(1)),/มีรหัส/);await rejects(()=>execute('teacher-a','saveStudent',{...base(41),studentNumber:1}),/เลขที่ซ้ำ/);await rejects(()=>execute('teacher-a','saveStudent',{...base(41),firstName:''}));await rejects(()=>execute('teacher-b','students',{classId:first.id}),/ไม่มีสิทธิ์/);await rejects(()=>execute('teacher-b','saveStudent',{...base(41)}),/ไม่มีสิทธิ์/);await rejects(()=>execute('admin-b','studentDetail',{studentId:roster[0].id}),/ไม่พบ/)});
 const pins=[];for(const s of roster)pins.push((await execute('teacher-a','resetPin',{studentId:s.id})).pin);
 const room=await execute('teacher-a','createRoom',{name:'ทดสอบ 40 คน',classIds:[first.id],levelId:6,mode:'challenge',difficulty:'normal',timeLimit:1200,attemptLimit:5,hint:true,leaderboard:true});
 await test('Room code plus student code cannot impersonate a student without PIN',async()=>{await rejects(()=>execute('anon-wrong','join',{code:room.code,studentCode:roster[0].studentCode,pin:'000000'},'wrong-ip'),/ข้อมูลเข้าห้อง/);assert.equal((await db.doc('users/anon-wrong').get()).exists,false)});
 await test('40 concurrent join calls create 40 distinct members without duplicate students',async()=>{const joined=await Promise.all(roster.map((s,i)=>execute('student-'+i,'join',{code:room.code,studentCode:s.studentCode,pin:pins[i]},'join-'+i)));assert.equal(joined.length,40);const r=await execute('teacher-a','room',{roomId:room.id});assert.equal(r.memberCount,40);assert.equal(Object.keys(r.members).length,40);await execute('student-0','join',{code:room.code,studentCode:roster[0].studentCode,pin:pins[0]},'rejoin');assert.equal((await execute('teacher-a','room',{roomId:room.id})).memberCount,40)});
 await test('Student cannot switch identity in the same authenticated session',async()=>{await rejects(()=>execute('student-0','join',{code:room.code,studentCode:roster[1].studentCode,pin:pins[1]},'switch-ip'),/ออกจากระบบ/);await rejects(()=>execute('student-0','studentDetail',{studentId:roster[1].id}),/ไม่มีสิทธิ์/)});
 const extra=await execute('teacher-a','saveStudent',base(41)),extraPin=(await execute('teacher-a','resetPin',{studentId:extra.studentId})).pin;
 await test('41st member and unauthorized teacher controls are rejected',async()=>{await rejects(()=>execute('student-extra','join',{code:room.code,studentCode:'00041',pin:extraPin},'extra'),/ห้องเต็ม/);await rejects(()=>execute('teacher-b','controlRoom',{roomId:room.id,action:'start'}),/ไม่มีสิทธิ์/)});
 await execute('teacher-a','controlRoom',{roomId:room.id,action:'start'});
 await new Promise(r=>setTimeout(r,3100));
 let active=await execute('teacher-a','room',{roomId:room.id});
 await test('All members receive identical seed/difficulty and server countdown',async()=>{const states=await Promise.all(Array.from({length:40},(_,i)=>execute('student-'+i,'room',{roomId:room.id})));assert(states.every(r=>r.seed===active.seed&&r.difficulty===active.difficulty&&r.roundId===active.roundId));assert.equal(active.locked,true);assert(active.startsAt>0)});
 let attempts;
 await test('40 concurrent attempts get server timestamps and immutable student context',async()=>{attempts=await Promise.all(Array.from({length:40},(_,i)=>execute('student-'+i,'startAttempt',{roomId:room.id,requestId:'attempt-one'})));assert(attempts.every(a=>a.number===1&&a.classId===first.id&&a.academicYear===2569));assert.equal((await execute('student-0','startAttempt',{roomId:room.id,requestId:'attempt-one'})).id,attempts[0].id)});
 const solution=generateMap(getLevel(6),active.seed,active.difficulty).optimal,submission={program:{start:solution,key:[],touch:[],receive:[]},keyTriggers:0,prediction:-1,storyboard:[0,1,2,3],character:'mint',environment:'forest'};
 await test('Forged score / wrong owner / invalid commands rejected by server replay',async()=>{await rejects(()=>execute('student-1','submit',{attemptId:attempts[0].id,submission}),/ไม่ใช่การเล่น/);await rejects(()=>execute('student-0','submit',{attemptId:attempts[0].id,score:100,submission:{...submission,program:{start:[],key:[],touch:[],receive:[]}}}),/พาบอท/);await rejects(()=>execute('student-0','submit',{attemptId:attempts[0].id,submission:{...submission,program:{start:[{op:'teleport'}],key:[],touch:[],receive:[]}}}),/บล็อก/)});
 await test('40 server-replayed submissions produce final rankings; retries do not duplicate scores',async()=>{const scores=await Promise.all(attempts.map((a,i)=>execute('student-'+i,'submit',{attemptId:a.id,score:999999,submission})));assert(scores.every(s=>s.verified&&s.score<=100&&s.score>=50));await execute('student-0','submit',{attemptId:attempts[0].id,submission});assert.equal((await db.collection(`schools/${school}/scores`).get()).size,40);assert.equal((await execute('teacher-a','rankings',{roomId:room.id})).length,40)});
 await test('Pause / resume / leaderboard visibility enforce server state',async()=>{await execute('teacher-a','controlRoom',{roomId:room.id,action:'pause'});await rejects(()=>execute('student-0','startAttempt',{roomId:room.id,requestId:'paused'}),/รอครู/);await execute('teacher-a','controlRoom',{roomId:room.id,action:'resume'});await execute('teacher-a','controlRoom',{roomId:room.id,action:'hide'});await rejects(()=>execute('student-0','rankings',{roomId:room.id}),/ซ่อน/);await execute('teacher-a','controlRoom',{roomId:room.id,action:'show'});assert.equal((await execute('student-0','rankings',{roomId:room.id})).length,40)});
 await test('Workspace save/reload is isolated by verified student and round',async()=>{await execute('student-0','saveWorkspace',{roomId:room.id,roundId:active.roundId,draft:{workspace:{test:'owner-0'}}});assert.equal((await execute('student-0','loadWorkspace',{roomId:room.id})).draft.workspace.test,'owner-0');assert.equal(await execute('student-1','loadWorkspace',{roomId:room.id}),null)});
 await execute('teacher-a','controlRoom',{roomId:room.id,action:'end'});
 await test('Transfer preserves studentId and original score/enrollment context',async()=>{const old=roster[0];await execute('teacher-a','saveStudent',{...old,classId:next.id,studentNumber:1});const detail=await execute('teacher-a','studentDetail',{studentId:old.id});assert.equal(detail.student.id,old.id);assert.equal(detail.student.academicYear,2570);assert.equal(detail.scores[0].academicYear,2569);assert.equal(detail.scores[0].classId,first.id);assert.equal(detail.enrollments.length,2);const report=await execute('teacher-a','report',{classId:next.id,academicYear:2570});assert.equal(report.scores.length,0)});
 await test('Archive blocks existing session writes and new entry; restore retains scores',async()=>{const s=roster[1];await execute('teacher-a','saveStudent',{...s,status:'inactive'});await rejects(()=>execute('student-1','saveWorkspace',{roomId:room.id,roundId:active.roundId,draft:{}}),/สิทธิ์/);await rejects(()=>execute('new-session','join',{code:room.code,studentCode:s.studentCode,pin:pins[1]},'archived'),/ไม่สามารถ/);const now=(await execute('teacher-a','studentDetail',{studentId:s.id})).student;await execute('teacher-a','saveStudent',{...now,status:'active'});assert.equal((await execute('teacher-a','studentDetail',{studentId:s.id})).scores.length,1)});
 await test('PIN reset revokes previous mapped sessions',async()=>{await execute('teacher-a','resetPin',{studentId:roster[2].id});await rejects(()=>execute('student-2','me',{}),/สิทธิ์/)});
 await test('Firestore Security Rules deny registry, roles, credentials, score writes and cross-school room access',async()=>{const env=await initializeTestEnvironment({projectId:'demo-code-quest',firestore:{host:'127.0.0.1',port:8080,rules:fs.readFileSync('firebase/firestore.rules','utf8')}});try{const student=env.authenticatedContext('student-3').firestore(),teacher=env.authenticatedContext('teacher-b').firestore(),otherAdmin=env.authenticatedContext('admin-b').firestore(),anon=env.unauthenticatedContext().firestore();await assertSucceeds(getDoc(doc(student,`schools/${school}/rooms/${room.id}`)));for(const d of [student,teacher,otherAdmin,anon]){await assertFails(getDoc(doc(d,`schools/${school}/students/${roster[0].id}`)));await assertFails(getDoc(doc(d,`schools/${school}/student_credentials/${roster[0].id}`)));await assertFails(setDoc(doc(d,'users/student-3'),{role:'admin'}));await assertFails(setDoc(doc(d,`schools/${school}/scores/forged`),{score:100}))}await assertFails(getDoc(doc(teacher,`schools/${school}/rooms/${room.id}`)));await assertFails(getDoc(doc(otherAdmin,`schools/${school}/rooms/${room.id}`)));await assertFails(getDoc(doc(anon,`schools/${school}/rooms/${room.id}`)))}finally{await env.cleanup()}});
 await test('New round changes seed and cannot reuse old submissions',async()=>{await execute('teacher-a','controlRoom',{roomId:room.id,action:'new'});const r=await execute('teacher-a','room',{roomId:room.id});assert.notEqual(r.seed,active.seed);assert.notEqual(r.roundId,active.roundId);await rejects(()=>execute('student-3','submit',{attemptId:attempts[3].id,submission}),/รอบเปลี่ยน/)});
 await test('Custom missions validate every size and difficulty and reject impossible configurations',async()=>{const base=(await execute('admin-a','missions')).find(m=>m.level.id===2);for(const size of [5,7,9,11]){const m={...base,level:{...base.level,id:100+size,title:'Custom '+size,mapRules:{gridSize:size,layout:'bent',rotate:true,obstacleDensity:.6,itemIndex:2,gateIndex:4}},create:true};await execute('admin-a','saveMission',m);for(const difficulty of ['easy','normal','hard']){const map=generateMap(m.level,'CUSTOM-'+size,difficulty);assert.equal(map.size,size);assert(map.optimal.length>0);assert(map.path.every(p=>p.x>=0&&p.x<size&&p.z>=0&&p.z<size))}}await rejects(()=>execute('teacher-a','saveMission',base),/สิทธิ์/);await rejects(()=>execute('admin-a','saveMission',{...base,energy:true,startEnergy:1}),/พลังงาน/);assert((await execute('admin-a','missions')).some(m=>m.level.id===111))});
 await test('Historical reports retain original class and term after transfer',async()=>{const report=await execute('admin-a','report',{academicYear:2569,semester:1});assert(report.scores.some(s=>s.studentId===roster[0].id&&s.classId===first.id));assert(report.students.some(s=>s.id===roster[0].id&&s.classId===first.id))});
 await test('Model storage reports its unavailable configuration and rejects student administration',async()=>{const assets=await execute('admin-a','assets');assert.equal(assets.ready,false);await rejects(()=>execute('student-3','assets'),/สิทธิ์/)});
 await test('500-student registry imports and paginates complete historical reports without losing non-players',async()=>{const classes=[];for(let i=0;i<12;i++)classes.push(await execute('admin-a','saveClass',{className:'ป.4/'+(i+3),grade:'ป.4',roomNumber:String(i+3),academicYear:2569,semester:1,teacherIds:['teacher-a'],status:'active'}));const rows=Array.from({length:459},(_,i)=>({rowId:String(i+2),student:{...base(i+42),classId:classes[Math.floor(i/40)].id,studentNumber:i%40+1}}));for(let i=0;i<rows.length;i+=25){const result=await execute('admin-a','import',{jobId:'school-500',rows:rows.slice(i,i+25),preview:false,mode:'skip'});assert(result.every(r=>r.ok))}const ids=new Set();for(let page=1;page<=5;page++){const report=await execute('admin-a','report',{academicYear:2569,semester:1,page});assert.equal(report.total,500);assert.equal(report.students.length,100);for(const row of report.students)ids.add(row.rowId)}assert.equal(ids.size,500)});
 console.log(JSON.stringify({status:'PASS',checks,concurrentPlayers:40,backend:'Firestore + Auth Emulator',production:false}));await db.terminate();process.exit(0);
})().catch(e=>{console.error('FAIL',e);process.exit(1)});
